// Code generated by go-swagger; DO NOT EDIT.

package movies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new movies API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new movies API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new movies API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for movies API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	MoviesCreate(params *MoviesCreateParams, opts ...ClientOption) (*MoviesCreateOK, error)

	MoviesDelete(params *MoviesDeleteParams, opts ...ClientOption) (*MoviesDeleteNoContent, error)

	MoviesList(params *MoviesListParams, opts ...ClientOption) (*MoviesListOK, error)

	MoviesShow(params *MoviesShowParams, opts ...ClientOption) (*MoviesShowOK, error)

	MoviesUpdate(params *MoviesUpdateParams, opts ...ClientOption) (*MoviesUpdateOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
MoviesCreate creates movie

Create movie
*/
func (a *Client) MoviesCreate(params *MoviesCreateParams, opts ...ClientOption) (*MoviesCreateOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewMoviesCreateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "MoviesCreate",
		Method:             "POST",
		PathPattern:        "/movies",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &MoviesCreateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*MoviesCreateOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for MoviesCreate: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
MoviesDelete deletes movie

Delete movie
*/
func (a *Client) MoviesDelete(params *MoviesDeleteParams, opts ...ClientOption) (*MoviesDeleteNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewMoviesDeleteParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "MoviesDelete",
		Method:             "DELETE",
		PathPattern:        "/movies/{movieID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &MoviesDeleteReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*MoviesDeleteNoContent)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for MoviesDelete: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
MoviesList lists movies

List movies
*/
func (a *Client) MoviesList(params *MoviesListParams, opts ...ClientOption) (*MoviesListOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewMoviesListParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "MoviesList",
		Method:             "GET",
		PathPattern:        "/movies",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &MoviesListReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*MoviesListOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for MoviesList: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
MoviesShow shows movie

Show movie
*/
func (a *Client) MoviesShow(params *MoviesShowParams, opts ...ClientOption) (*MoviesShowOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewMoviesShowParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "MoviesShow",
		Method:             "GET",
		PathPattern:        "/movies/{movieID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &MoviesShowReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*MoviesShowOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for MoviesShow: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
MoviesUpdate updates movie

Update movie
*/
func (a *Client) MoviesUpdate(params *MoviesUpdateParams, opts ...ClientOption) (*MoviesUpdateOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewMoviesUpdateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "MoviesUpdate",
		Method:             "PUT",
		PathPattern:        "/movies/{movieID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &MoviesUpdateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*MoviesUpdateOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for MoviesUpdate: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
