// Code generated by go-swagger; DO NOT EDIT.

package movies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// MoviesUpdateReader is a Reader for the MoviesUpdate structure.
type MoviesUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MoviesUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewMoviesUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewMoviesUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewMoviesUpdateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewMoviesUpdateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /movies/{movieID}] MoviesUpdate", response, response.Code())
	}
}

// NewMoviesUpdateOK creates a MoviesUpdateOK with default headers values
func NewMoviesUpdateOK() *MoviesUpdateOK {
	return &MoviesUpdateOK{}
}

/*
MoviesUpdateOK describes a response with status code 200, with default header values.

OK
*/
type MoviesUpdateOK struct {
	Payload *models.APIMovieResponse
}

// IsSuccess returns true when this movies update o k response has a 2xx status code
func (o *MoviesUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this movies update o k response has a 3xx status code
func (o *MoviesUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies update o k response has a 4xx status code
func (o *MoviesUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this movies update o k response has a 5xx status code
func (o *MoviesUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this movies update o k response a status code equal to that given
func (o *MoviesUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the movies update o k response
func (o *MoviesUpdateOK) Code() int {
	return 200
}

func (o *MoviesUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /movies/{movieID}][%d] moviesUpdateOK %s", 200, payload)
}

func (o *MoviesUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /movies/{movieID}][%d] moviesUpdateOK %s", 200, payload)
}

func (o *MoviesUpdateOK) GetPayload() *models.APIMovieResponse {
	return o.Payload
}

func (o *MoviesUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIMovieResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewMoviesUpdateBadRequest creates a MoviesUpdateBadRequest with default headers values
func NewMoviesUpdateBadRequest() *MoviesUpdateBadRequest {
	return &MoviesUpdateBadRequest{}
}

/*
MoviesUpdateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type MoviesUpdateBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this movies update bad request response has a 2xx status code
func (o *MoviesUpdateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this movies update bad request response has a 3xx status code
func (o *MoviesUpdateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies update bad request response has a 4xx status code
func (o *MoviesUpdateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this movies update bad request response has a 5xx status code
func (o *MoviesUpdateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this movies update bad request response a status code equal to that given
func (o *MoviesUpdateBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the movies update bad request response
func (o *MoviesUpdateBadRequest) Code() int {
	return 400
}

func (o *MoviesUpdateBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /movies/{movieID}][%d] moviesUpdateBadRequest %s", 400, payload)
}

func (o *MoviesUpdateBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /movies/{movieID}][%d] moviesUpdateBadRequest %s", 400, payload)
}

func (o *MoviesUpdateBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *MoviesUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewMoviesUpdateNotFound creates a MoviesUpdateNotFound with default headers values
func NewMoviesUpdateNotFound() *MoviesUpdateNotFound {
	return &MoviesUpdateNotFound{}
}

/*
MoviesUpdateNotFound describes a response with status code 404, with default header values.

Not Found
*/
type MoviesUpdateNotFound struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this movies update not found response has a 2xx status code
func (o *MoviesUpdateNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this movies update not found response has a 3xx status code
func (o *MoviesUpdateNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies update not found response has a 4xx status code
func (o *MoviesUpdateNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this movies update not found response has a 5xx status code
func (o *MoviesUpdateNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this movies update not found response a status code equal to that given
func (o *MoviesUpdateNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the movies update not found response
func (o *MoviesUpdateNotFound) Code() int {
	return 404
}

func (o *MoviesUpdateNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /movies/{movieID}][%d] moviesUpdateNotFound %s", 404, payload)
}

func (o *MoviesUpdateNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /movies/{movieID}][%d] moviesUpdateNotFound %s", 404, payload)
}

func (o *MoviesUpdateNotFound) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *MoviesUpdateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewMoviesUpdateInternalServerError creates a MoviesUpdateInternalServerError with default headers values
func NewMoviesUpdateInternalServerError() *MoviesUpdateInternalServerError {
	return &MoviesUpdateInternalServerError{}
}

/*
MoviesUpdateInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type MoviesUpdateInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this movies update internal server error response has a 2xx status code
func (o *MoviesUpdateInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this movies update internal server error response has a 3xx status code
func (o *MoviesUpdateInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies update internal server error response has a 4xx status code
func (o *MoviesUpdateInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this movies update internal server error response has a 5xx status code
func (o *MoviesUpdateInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this movies update internal server error response a status code equal to that given
func (o *MoviesUpdateInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the movies update internal server error response
func (o *MoviesUpdateInternalServerError) Code() int {
	return 500
}

func (o *MoviesUpdateInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /movies/{movieID}][%d] moviesUpdateInternalServerError %s", 500, payload)
}

func (o *MoviesUpdateInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /movies/{movieID}][%d] moviesUpdateInternalServerError %s", 500, payload)
}

func (o *MoviesUpdateInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *MoviesUpdateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
