// Code generated by go-swagger; DO NOT EDIT.

package movies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMoviesDeleteParams creates a new MoviesDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMoviesDeleteParams() *MoviesDeleteParams {
	return &MoviesDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMoviesDeleteParamsWithTimeout creates a new MoviesDeleteParams object
// with the ability to set a timeout on a request.
func NewMoviesDeleteParamsWithTimeout(timeout time.Duration) *MoviesDeleteParams {
	return &MoviesDeleteParams{
		timeout: timeout,
	}
}

// NewMoviesDeleteParamsWithContext creates a new MoviesDeleteParams object
// with the ability to set a context for a request.
func NewMoviesDeleteParamsWithContext(ctx context.Context) *MoviesDeleteParams {
	return &MoviesDeleteParams{
		Context: ctx,
	}
}

// NewMoviesDeleteParamsWithHTTPClient creates a new MoviesDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewMoviesDeleteParamsWithHTTPClient(client *http.Client) *MoviesDeleteParams {
	return &MoviesDeleteParams{
		HTTPClient: client,
	}
}

/*
MoviesDeleteParams contains all the parameters to send to the API endpoint

	for the movies delete operation.

	Typically these are written to a http.Request.
*/
type MoviesDeleteParams struct {

	/* MovieID.

	   Movie ID

	   Format: uuid
	*/
	MovieID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the movies delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MoviesDeleteParams) WithDefaults() *MoviesDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the movies delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MoviesDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the movies delete params
func (o *MoviesDeleteParams) WithTimeout(timeout time.Duration) *MoviesDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the movies delete params
func (o *MoviesDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the movies delete params
func (o *MoviesDeleteParams) WithContext(ctx context.Context) *MoviesDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the movies delete params
func (o *MoviesDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the movies delete params
func (o *MoviesDeleteParams) WithHTTPClient(client *http.Client) *MoviesDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the movies delete params
func (o *MoviesDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMovieID adds the movieID to the movies delete params
func (o *MoviesDeleteParams) WithMovieID(movieID strfmt.UUID) *MoviesDeleteParams {
	o.SetMovieID(movieID)
	return o
}

// SetMovieID adds the movieId to the movies delete params
func (o *MoviesDeleteParams) SetMovieID(movieID strfmt.UUID) {
	o.MovieID = movieID
}

// WriteToRequest writes these params to a swagger request
func (o *MoviesDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param movieID
	if err := r.SetPathParam("movieID", o.MovieID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
