// Code generated by go-swagger; DO NOT EDIT.

package movies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// MoviesShowReader is a Reader for the MoviesShow structure.
type MoviesShowReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MoviesShowReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewMoviesShowOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewMoviesShowBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewMoviesShowNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewMoviesShowInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /movies/{movieID}] MoviesShow", response, response.Code())
	}
}

// NewMoviesShowOK creates a MoviesShowOK with default headers values
func NewMoviesShowOK() *MoviesShowOK {
	return &MoviesShowOK{}
}

/*
MoviesShowOK describes a response with status code 200, with default header values.

OK
*/
type MoviesShowOK struct {
	Payload *models.APIMovieResponse
}

// IsSuccess returns true when this movies show o k response has a 2xx status code
func (o *MoviesShowOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this movies show o k response has a 3xx status code
func (o *MoviesShowOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies show o k response has a 4xx status code
func (o *MoviesShowOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this movies show o k response has a 5xx status code
func (o *MoviesShowOK) IsServerError() bool {
	return false
}

// IsCode returns true when this movies show o k response a status code equal to that given
func (o *MoviesShowOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the movies show o k response
func (o *MoviesShowOK) Code() int {
	return 200
}

func (o *MoviesShowOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies/{movieID}][%d] moviesShowOK %s", 200, payload)
}

func (o *MoviesShowOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies/{movieID}][%d] moviesShowOK %s", 200, payload)
}

func (o *MoviesShowOK) GetPayload() *models.APIMovieResponse {
	return o.Payload
}

func (o *MoviesShowOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIMovieResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewMoviesShowBadRequest creates a MoviesShowBadRequest with default headers values
func NewMoviesShowBadRequest() *MoviesShowBadRequest {
	return &MoviesShowBadRequest{}
}

/*
MoviesShowBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type MoviesShowBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this movies show bad request response has a 2xx status code
func (o *MoviesShowBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this movies show bad request response has a 3xx status code
func (o *MoviesShowBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies show bad request response has a 4xx status code
func (o *MoviesShowBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this movies show bad request response has a 5xx status code
func (o *MoviesShowBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this movies show bad request response a status code equal to that given
func (o *MoviesShowBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the movies show bad request response
func (o *MoviesShowBadRequest) Code() int {
	return 400
}

func (o *MoviesShowBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies/{movieID}][%d] moviesShowBadRequest %s", 400, payload)
}

func (o *MoviesShowBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies/{movieID}][%d] moviesShowBadRequest %s", 400, payload)
}

func (o *MoviesShowBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *MoviesShowBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewMoviesShowNotFound creates a MoviesShowNotFound with default headers values
func NewMoviesShowNotFound() *MoviesShowNotFound {
	return &MoviesShowNotFound{}
}

/*
MoviesShowNotFound describes a response with status code 404, with default header values.

Not Found
*/
type MoviesShowNotFound struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this movies show not found response has a 2xx status code
func (o *MoviesShowNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this movies show not found response has a 3xx status code
func (o *MoviesShowNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies show not found response has a 4xx status code
func (o *MoviesShowNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this movies show not found response has a 5xx status code
func (o *MoviesShowNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this movies show not found response a status code equal to that given
func (o *MoviesShowNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the movies show not found response
func (o *MoviesShowNotFound) Code() int {
	return 404
}

func (o *MoviesShowNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies/{movieID}][%d] moviesShowNotFound %s", 404, payload)
}

func (o *MoviesShowNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies/{movieID}][%d] moviesShowNotFound %s", 404, payload)
}

func (o *MoviesShowNotFound) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *MoviesShowNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewMoviesShowInternalServerError creates a MoviesShowInternalServerError with default headers values
func NewMoviesShowInternalServerError() *MoviesShowInternalServerError {
	return &MoviesShowInternalServerError{}
}

/*
MoviesShowInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type MoviesShowInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this movies show internal server error response has a 2xx status code
func (o *MoviesShowInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this movies show internal server error response has a 3xx status code
func (o *MoviesShowInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies show internal server error response has a 4xx status code
func (o *MoviesShowInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this movies show internal server error response has a 5xx status code
func (o *MoviesShowInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this movies show internal server error response a status code equal to that given
func (o *MoviesShowInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the movies show internal server error response
func (o *MoviesShowInternalServerError) Code() int {
	return 500
}

func (o *MoviesShowInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies/{movieID}][%d] moviesShowInternalServerError %s", 500, payload)
}

func (o *MoviesShowInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies/{movieID}][%d] moviesShowInternalServerError %s", 500, payload)
}

func (o *MoviesShowInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *MoviesShowInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
