// Code generated by go-swagger; DO NOT EDIT.

package movies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// MoviesDeleteReader is a Reader for the MoviesDelete structure.
type MoviesDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MoviesDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewMoviesDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewMoviesDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewMoviesDeleteNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewMoviesDeleteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /movies/{movieID}] MoviesDelete", response, response.Code())
	}
}

// NewMoviesDeleteNoContent creates a MoviesDeleteNoContent with default headers values
func NewMoviesDeleteNoContent() *MoviesDeleteNoContent {
	return &MoviesDeleteNoContent{}
}

/*
MoviesDeleteNoContent describes a response with status code 204, with default header values.

No Content
*/
type MoviesDeleteNoContent struct {
}

// IsSuccess returns true when this movies delete no content response has a 2xx status code
func (o *MoviesDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this movies delete no content response has a 3xx status code
func (o *MoviesDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies delete no content response has a 4xx status code
func (o *MoviesDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this movies delete no content response has a 5xx status code
func (o *MoviesDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this movies delete no content response a status code equal to that given
func (o *MoviesDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the movies delete no content response
func (o *MoviesDeleteNoContent) Code() int {
	return 204
}

func (o *MoviesDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /movies/{movieID}][%d] moviesDeleteNoContent", 204)
}

func (o *MoviesDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /movies/{movieID}][%d] moviesDeleteNoContent", 204)
}

func (o *MoviesDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewMoviesDeleteBadRequest creates a MoviesDeleteBadRequest with default headers values
func NewMoviesDeleteBadRequest() *MoviesDeleteBadRequest {
	return &MoviesDeleteBadRequest{}
}

/*
MoviesDeleteBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type MoviesDeleteBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this movies delete bad request response has a 2xx status code
func (o *MoviesDeleteBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this movies delete bad request response has a 3xx status code
func (o *MoviesDeleteBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies delete bad request response has a 4xx status code
func (o *MoviesDeleteBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this movies delete bad request response has a 5xx status code
func (o *MoviesDeleteBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this movies delete bad request response a status code equal to that given
func (o *MoviesDeleteBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the movies delete bad request response
func (o *MoviesDeleteBadRequest) Code() int {
	return 400
}

func (o *MoviesDeleteBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /movies/{movieID}][%d] moviesDeleteBadRequest %s", 400, payload)
}

func (o *MoviesDeleteBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /movies/{movieID}][%d] moviesDeleteBadRequest %s", 400, payload)
}

func (o *MoviesDeleteBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *MoviesDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewMoviesDeleteNotFound creates a MoviesDeleteNotFound with default headers values
func NewMoviesDeleteNotFound() *MoviesDeleteNotFound {
	return &MoviesDeleteNotFound{}
}

/*
MoviesDeleteNotFound describes a response with status code 404, with default header values.

Not Found
*/
type MoviesDeleteNotFound struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this movies delete not found response has a 2xx status code
func (o *MoviesDeleteNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this movies delete not found response has a 3xx status code
func (o *MoviesDeleteNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies delete not found response has a 4xx status code
func (o *MoviesDeleteNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this movies delete not found response has a 5xx status code
func (o *MoviesDeleteNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this movies delete not found response a status code equal to that given
func (o *MoviesDeleteNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the movies delete not found response
func (o *MoviesDeleteNotFound) Code() int {
	return 404
}

func (o *MoviesDeleteNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /movies/{movieID}][%d] moviesDeleteNotFound %s", 404, payload)
}

func (o *MoviesDeleteNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /movies/{movieID}][%d] moviesDeleteNotFound %s", 404, payload)
}

func (o *MoviesDeleteNotFound) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *MoviesDeleteNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewMoviesDeleteInternalServerError creates a MoviesDeleteInternalServerError with default headers values
func NewMoviesDeleteInternalServerError() *MoviesDeleteInternalServerError {
	return &MoviesDeleteInternalServerError{}
}

/*
MoviesDeleteInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type MoviesDeleteInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this movies delete internal server error response has a 2xx status code
func (o *MoviesDeleteInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this movies delete internal server error response has a 3xx status code
func (o *MoviesDeleteInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies delete internal server error response has a 4xx status code
func (o *MoviesDeleteInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this movies delete internal server error response has a 5xx status code
func (o *MoviesDeleteInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this movies delete internal server error response a status code equal to that given
func (o *MoviesDeleteInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the movies delete internal server error response
func (o *MoviesDeleteInternalServerError) Code() int {
	return 500
}

func (o *MoviesDeleteInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /movies/{movieID}][%d] moviesDeleteInternalServerError %s", 500, payload)
}

func (o *MoviesDeleteInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /movies/{movieID}][%d] moviesDeleteInternalServerError %s", 500, payload)
}

func (o *MoviesDeleteInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *MoviesDeleteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
