// Code generated by go-swagger; DO NOT EDIT.

package movies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMoviesShowParams creates a new MoviesShowParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMoviesShowParams() *MoviesShowParams {
	return &MoviesShowParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMoviesShowParamsWithTimeout creates a new MoviesShowParams object
// with the ability to set a timeout on a request.
func NewMoviesShowParamsWithTimeout(timeout time.Duration) *MoviesShowParams {
	return &MoviesShowParams{
		timeout: timeout,
	}
}

// NewMoviesShowParamsWithContext creates a new MoviesShowParams object
// with the ability to set a context for a request.
func NewMoviesShowParamsWithContext(ctx context.Context) *MoviesShowParams {
	return &MoviesShowParams{
		Context: ctx,
	}
}

// NewMoviesShowParamsWithHTTPClient creates a new MoviesShowParams object
// with the ability to set a custom HTTPClient for a request.
func NewMoviesShowParamsWithHTTPClient(client *http.Client) *MoviesShowParams {
	return &MoviesShowParams{
		HTTPClient: client,
	}
}

/*
MoviesShowParams contains all the parameters to send to the API endpoint

	for the movies show operation.

	Typically these are written to a http.Request.
*/
type MoviesShowParams struct {

	/* MovieID.

	   Movie ID

	   Format: uuid
	*/
	MovieID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the movies show params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MoviesShowParams) WithDefaults() *MoviesShowParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the movies show params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MoviesShowParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the movies show params
func (o *MoviesShowParams) WithTimeout(timeout time.Duration) *MoviesShowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the movies show params
func (o *MoviesShowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the movies show params
func (o *MoviesShowParams) WithContext(ctx context.Context) *MoviesShowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the movies show params
func (o *MoviesShowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the movies show params
func (o *MoviesShowParams) WithHTTPClient(client *http.Client) *MoviesShowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the movies show params
func (o *MoviesShowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMovieID adds the movieID to the movies show params
func (o *MoviesShowParams) WithMovieID(movieID strfmt.UUID) *MoviesShowParams {
	o.SetMovieID(movieID)
	return o
}

// SetMovieID adds the movieId to the movies show params
func (o *MoviesShowParams) SetMovieID(movieID strfmt.UUID) {
	o.MovieID = movieID
}

// WriteToRequest writes these params to a swagger request
func (o *MoviesShowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param movieID
	if err := r.SetPathParam("movieID", o.MovieID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
