// Code generated by go-swagger; DO NOT EDIT.

package movies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewMoviesListParams creates a new MoviesListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMoviesListParams() *MoviesListParams {
	return &MoviesListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMoviesListParamsWithTimeout creates a new MoviesListParams object
// with the ability to set a timeout on a request.
func NewMoviesListParamsWithTimeout(timeout time.Duration) *MoviesListParams {
	return &MoviesListParams{
		timeout: timeout,
	}
}

// NewMoviesListParamsWithContext creates a new MoviesListParams object
// with the ability to set a context for a request.
func NewMoviesListParamsWithContext(ctx context.Context) *MoviesListParams {
	return &MoviesListParams{
		Context: ctx,
	}
}

// NewMoviesListParamsWithHTTPClient creates a new MoviesListParams object
// with the ability to set a custom HTTPClient for a request.
func NewMoviesListParamsWithHTTPClient(client *http.Client) *MoviesListParams {
	return &MoviesListParams{
		HTTPClient: client,
	}
}

/*
MoviesListParams contains all the parameters to send to the API endpoint

	for the movies list operation.

	Typically these are written to a http.Request.
*/
type MoviesListParams struct {

	/* Limit.

	   Limit the number of responses

	   Default: 10
	*/
	Limit *int64

	/* Offset.

	   Offset the first response
	*/
	Offset *int64

	/* Sort.

	   Sort results
	*/
	Sort *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the movies list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MoviesListParams) WithDefaults() *MoviesListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the movies list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MoviesListParams) SetDefaults() {
	var (
		limitDefault = int64(10)

		offsetDefault = int64(0)
	)

	val := MoviesListParams{
		Limit:  &limitDefault,
		Offset: &offsetDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the movies list params
func (o *MoviesListParams) WithTimeout(timeout time.Duration) *MoviesListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the movies list params
func (o *MoviesListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the movies list params
func (o *MoviesListParams) WithContext(ctx context.Context) *MoviesListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the movies list params
func (o *MoviesListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the movies list params
func (o *MoviesListParams) WithHTTPClient(client *http.Client) *MoviesListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the movies list params
func (o *MoviesListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the movies list params
func (o *MoviesListParams) WithLimit(limit *int64) *MoviesListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the movies list params
func (o *MoviesListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the movies list params
func (o *MoviesListParams) WithOffset(offset *int64) *MoviesListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the movies list params
func (o *MoviesListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithSort adds the sort to the movies list params
func (o *MoviesListParams) WithSort(sort *string) *MoviesListParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the movies list params
func (o *MoviesListParams) SetSort(sort *string) {
	o.Sort = sort
}

// WriteToRequest writes these params to a swagger request
func (o *MoviesListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.Sort != nil {

		// query param sort
		var qrSort string

		if o.Sort != nil {
			qrSort = *o.Sort
		}
		qSort := qrSort
		if qSort != "" {

			if err := r.SetQueryParam("sort", qSort); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
