// Code generated by go-swagger; DO NOT EDIT.

package movies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// MoviesCreateReader is a Reader for the MoviesCreate structure.
type MoviesCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MoviesCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewMoviesCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewMoviesCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewMoviesCreateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewMoviesCreateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /movies] MoviesCreate", response, response.Code())
	}
}

// NewMoviesCreateOK creates a MoviesCreateOK with default headers values
func NewMoviesCreateOK() *MoviesCreateOK {
	return &MoviesCreateOK{}
}

/*
MoviesCreateOK describes a response with status code 200, with default header values.

OK
*/
type MoviesCreateOK struct {
	Payload *models.APIMovieResponse
}

// IsSuccess returns true when this movies create o k response has a 2xx status code
func (o *MoviesCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this movies create o k response has a 3xx status code
func (o *MoviesCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies create o k response has a 4xx status code
func (o *MoviesCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this movies create o k response has a 5xx status code
func (o *MoviesCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this movies create o k response a status code equal to that given
func (o *MoviesCreateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the movies create o k response
func (o *MoviesCreateOK) Code() int {
	return 200
}

func (o *MoviesCreateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /movies][%d] moviesCreateOK %s", 200, payload)
}

func (o *MoviesCreateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /movies][%d] moviesCreateOK %s", 200, payload)
}

func (o *MoviesCreateOK) GetPayload() *models.APIMovieResponse {
	return o.Payload
}

func (o *MoviesCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIMovieResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewMoviesCreateBadRequest creates a MoviesCreateBadRequest with default headers values
func NewMoviesCreateBadRequest() *MoviesCreateBadRequest {
	return &MoviesCreateBadRequest{}
}

/*
MoviesCreateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type MoviesCreateBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this movies create bad request response has a 2xx status code
func (o *MoviesCreateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this movies create bad request response has a 3xx status code
func (o *MoviesCreateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies create bad request response has a 4xx status code
func (o *MoviesCreateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this movies create bad request response has a 5xx status code
func (o *MoviesCreateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this movies create bad request response a status code equal to that given
func (o *MoviesCreateBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the movies create bad request response
func (o *MoviesCreateBadRequest) Code() int {
	return 400
}

func (o *MoviesCreateBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /movies][%d] moviesCreateBadRequest %s", 400, payload)
}

func (o *MoviesCreateBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /movies][%d] moviesCreateBadRequest %s", 400, payload)
}

func (o *MoviesCreateBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *MoviesCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewMoviesCreateNotFound creates a MoviesCreateNotFound with default headers values
func NewMoviesCreateNotFound() *MoviesCreateNotFound {
	return &MoviesCreateNotFound{}
}

/*
MoviesCreateNotFound describes a response with status code 404, with default header values.

Not Found
*/
type MoviesCreateNotFound struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this movies create not found response has a 2xx status code
func (o *MoviesCreateNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this movies create not found response has a 3xx status code
func (o *MoviesCreateNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies create not found response has a 4xx status code
func (o *MoviesCreateNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this movies create not found response has a 5xx status code
func (o *MoviesCreateNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this movies create not found response a status code equal to that given
func (o *MoviesCreateNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the movies create not found response
func (o *MoviesCreateNotFound) Code() int {
	return 404
}

func (o *MoviesCreateNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /movies][%d] moviesCreateNotFound %s", 404, payload)
}

func (o *MoviesCreateNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /movies][%d] moviesCreateNotFound %s", 404, payload)
}

func (o *MoviesCreateNotFound) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *MoviesCreateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewMoviesCreateInternalServerError creates a MoviesCreateInternalServerError with default headers values
func NewMoviesCreateInternalServerError() *MoviesCreateInternalServerError {
	return &MoviesCreateInternalServerError{}
}

/*
MoviesCreateInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type MoviesCreateInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this movies create internal server error response has a 2xx status code
func (o *MoviesCreateInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this movies create internal server error response has a 3xx status code
func (o *MoviesCreateInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies create internal server error response has a 4xx status code
func (o *MoviesCreateInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this movies create internal server error response has a 5xx status code
func (o *MoviesCreateInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this movies create internal server error response a status code equal to that given
func (o *MoviesCreateInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the movies create internal server error response
func (o *MoviesCreateInternalServerError) Code() int {
	return 500
}

func (o *MoviesCreateInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /movies][%d] moviesCreateInternalServerError %s", 500, payload)
}

func (o *MoviesCreateInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /movies][%d] moviesCreateInternalServerError %s", 500, payload)
}

func (o *MoviesCreateInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *MoviesCreateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
