// Code generated by go-swagger; DO NOT EDIT.

package movies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// NewMoviesCreateParams creates a new MoviesCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMoviesCreateParams() *MoviesCreateParams {
	return &MoviesCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMoviesCreateParamsWithTimeout creates a new MoviesCreateParams object
// with the ability to set a timeout on a request.
func NewMoviesCreateParamsWithTimeout(timeout time.Duration) *MoviesCreateParams {
	return &MoviesCreateParams{
		timeout: timeout,
	}
}

// NewMoviesCreateParamsWithContext creates a new MoviesCreateParams object
// with the ability to set a context for a request.
func NewMoviesCreateParamsWithContext(ctx context.Context) *MoviesCreateParams {
	return &MoviesCreateParams{
		Context: ctx,
	}
}

// NewMoviesCreateParamsWithHTTPClient creates a new MoviesCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewMoviesCreateParamsWithHTTPClient(client *http.Client) *MoviesCreateParams {
	return &MoviesCreateParams{
		HTTPClient: client,
	}
}

/*
MoviesCreateParams contains all the parameters to send to the API endpoint

	for the movies create operation.

	Typically these are written to a http.Request.
*/
type MoviesCreateParams struct {

	/* Request.

	   request body
	*/
	Request *models.APIMovieRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the movies create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MoviesCreateParams) WithDefaults() *MoviesCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the movies create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MoviesCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the movies create params
func (o *MoviesCreateParams) WithTimeout(timeout time.Duration) *MoviesCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the movies create params
func (o *MoviesCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the movies create params
func (o *MoviesCreateParams) WithContext(ctx context.Context) *MoviesCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the movies create params
func (o *MoviesCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the movies create params
func (o *MoviesCreateParams) WithHTTPClient(client *http.Client) *MoviesCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the movies create params
func (o *MoviesCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the movies create params
func (o *MoviesCreateParams) WithRequest(request *models.APIMovieRequest) *MoviesCreateParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the movies create params
func (o *MoviesCreateParams) SetRequest(request *models.APIMovieRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *MoviesCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
