// Code generated by go-swagger; DO NOT EDIT.

package movies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// MoviesListReader is a Reader for the MoviesList structure.
type MoviesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MoviesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewMoviesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewMoviesListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewMoviesListNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewMoviesListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /movies] MoviesList", response, response.Code())
	}
}

// NewMoviesListOK creates a MoviesListOK with default headers values
func NewMoviesListOK() *MoviesListOK {
	return &MoviesListOK{}
}

/*
MoviesListOK describes a response with status code 200, with default header values.

OK
*/
type MoviesListOK struct {
	Payload []*models.APIMovieResponse
}

// IsSuccess returns true when this movies list o k response has a 2xx status code
func (o *MoviesListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this movies list o k response has a 3xx status code
func (o *MoviesListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies list o k response has a 4xx status code
func (o *MoviesListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this movies list o k response has a 5xx status code
func (o *MoviesListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this movies list o k response a status code equal to that given
func (o *MoviesListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the movies list o k response
func (o *MoviesListOK) Code() int {
	return 200
}

func (o *MoviesListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies][%d] moviesListOK %s", 200, payload)
}

func (o *MoviesListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies][%d] moviesListOK %s", 200, payload)
}

func (o *MoviesListOK) GetPayload() []*models.APIMovieResponse {
	return o.Payload
}

func (o *MoviesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewMoviesListBadRequest creates a MoviesListBadRequest with default headers values
func NewMoviesListBadRequest() *MoviesListBadRequest {
	return &MoviesListBadRequest{}
}

/*
MoviesListBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type MoviesListBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this movies list bad request response has a 2xx status code
func (o *MoviesListBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this movies list bad request response has a 3xx status code
func (o *MoviesListBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies list bad request response has a 4xx status code
func (o *MoviesListBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this movies list bad request response has a 5xx status code
func (o *MoviesListBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this movies list bad request response a status code equal to that given
func (o *MoviesListBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the movies list bad request response
func (o *MoviesListBadRequest) Code() int {
	return 400
}

func (o *MoviesListBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies][%d] moviesListBadRequest %s", 400, payload)
}

func (o *MoviesListBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies][%d] moviesListBadRequest %s", 400, payload)
}

func (o *MoviesListBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *MoviesListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewMoviesListNotFound creates a MoviesListNotFound with default headers values
func NewMoviesListNotFound() *MoviesListNotFound {
	return &MoviesListNotFound{}
}

/*
MoviesListNotFound describes a response with status code 404, with default header values.

Not Found
*/
type MoviesListNotFound struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this movies list not found response has a 2xx status code
func (o *MoviesListNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this movies list not found response has a 3xx status code
func (o *MoviesListNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies list not found response has a 4xx status code
func (o *MoviesListNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this movies list not found response has a 5xx status code
func (o *MoviesListNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this movies list not found response a status code equal to that given
func (o *MoviesListNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the movies list not found response
func (o *MoviesListNotFound) Code() int {
	return 404
}

func (o *MoviesListNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies][%d] moviesListNotFound %s", 404, payload)
}

func (o *MoviesListNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies][%d] moviesListNotFound %s", 404, payload)
}

func (o *MoviesListNotFound) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *MoviesListNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewMoviesListInternalServerError creates a MoviesListInternalServerError with default headers values
func NewMoviesListInternalServerError() *MoviesListInternalServerError {
	return &MoviesListInternalServerError{}
}

/*
MoviesListInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type MoviesListInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this movies list internal server error response has a 2xx status code
func (o *MoviesListInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this movies list internal server error response has a 3xx status code
func (o *MoviesListInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies list internal server error response has a 4xx status code
func (o *MoviesListInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this movies list internal server error response has a 5xx status code
func (o *MoviesListInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this movies list internal server error response a status code equal to that given
func (o *MoviesListInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the movies list internal server error response
func (o *MoviesListInternalServerError) Code() int {
	return 500
}

func (o *MoviesListInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies][%d] moviesListInternalServerError %s", 500, payload)
}

func (o *MoviesListInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies][%d] moviesListInternalServerError %s", 500, payload)
}

func (o *MoviesListInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *MoviesListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
