// Code generated by go-swagger; DO NOT EDIT.

package movies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// MoviesListReader is a Reader for the MoviesList structure.
type MoviesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MoviesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewMoviesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewMoviesListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewMoviesListNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewMoviesListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /movies] MoviesList", response, response.Code())
	}
}

// NewMoviesListOK creates a MoviesListOK with default headers values
func NewMoviesListOK() *MoviesListOK {
	return &MoviesListOK{}
}

/*
MoviesListOK describes a response with status code 200, with default header values.

OK
*/
type MoviesListOK struct {
	Payload *MoviesListOKBody
}

// IsSuccess returns true when this movies list o k response has a 2xx status code
func (o *MoviesListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this movies list o k response has a 3xx status code
func (o *MoviesListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies list o k response has a 4xx status code
func (o *MoviesListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this movies list o k response has a 5xx status code
func (o *MoviesListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this movies list o k response a status code equal to that given
func (o *MoviesListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the movies list o k response
func (o *MoviesListOK) Code() int {
	return 200
}

func (o *MoviesListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies][%d] moviesListOK %s", 200, payload)
}

func (o *MoviesListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies][%d] moviesListOK %s", 200, payload)
}

func (o *MoviesListOK) GetPayload() *MoviesListOKBody {
	return o.Payload
}

func (o *MoviesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(MoviesListOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewMoviesListBadRequest creates a MoviesListBadRequest with default headers values
func NewMoviesListBadRequest() *MoviesListBadRequest {
	return &MoviesListBadRequest{}
}

/*
MoviesListBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type MoviesListBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this movies list bad request response has a 2xx status code
func (o *MoviesListBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this movies list bad request response has a 3xx status code
func (o *MoviesListBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies list bad request response has a 4xx status code
func (o *MoviesListBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this movies list bad request response has a 5xx status code
func (o *MoviesListBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this movies list bad request response a status code equal to that given
func (o *MoviesListBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the movies list bad request response
func (o *MoviesListBadRequest) Code() int {
	return 400
}

func (o *MoviesListBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies][%d] moviesListBadRequest %s", 400, payload)
}

func (o *MoviesListBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies][%d] moviesListBadRequest %s", 400, payload)
}

func (o *MoviesListBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *MoviesListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewMoviesListNotFound creates a MoviesListNotFound with default headers values
func NewMoviesListNotFound() *MoviesListNotFound {
	return &MoviesListNotFound{}
}

/*
MoviesListNotFound describes a response with status code 404, with default header values.

Not Found
*/
type MoviesListNotFound struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this movies list not found response has a 2xx status code
func (o *MoviesListNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this movies list not found response has a 3xx status code
func (o *MoviesListNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies list not found response has a 4xx status code
func (o *MoviesListNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this movies list not found response has a 5xx status code
func (o *MoviesListNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this movies list not found response a status code equal to that given
func (o *MoviesListNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the movies list not found response
func (o *MoviesListNotFound) Code() int {
	return 404
}

func (o *MoviesListNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies][%d] moviesListNotFound %s", 404, payload)
}

func (o *MoviesListNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies][%d] moviesListNotFound %s", 404, payload)
}

func (o *MoviesListNotFound) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *MoviesListNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewMoviesListInternalServerError creates a MoviesListInternalServerError with default headers values
func NewMoviesListInternalServerError() *MoviesListInternalServerError {
	return &MoviesListInternalServerError{}
}

/*
MoviesListInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type MoviesListInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this movies list internal server error response has a 2xx status code
func (o *MoviesListInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this movies list internal server error response has a 3xx status code
func (o *MoviesListInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this movies list internal server error response has a 4xx status code
func (o *MoviesListInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this movies list internal server error response has a 5xx status code
func (o *MoviesListInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this movies list internal server error response a status code equal to that given
func (o *MoviesListInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the movies list internal server error response
func (o *MoviesListInternalServerError) Code() int {
	return 500
}

func (o *MoviesListInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies][%d] moviesListInternalServerError %s", 500, payload)
}

func (o *MoviesListInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /movies][%d] moviesListInternalServerError %s", 500, payload)
}

func (o *MoviesListInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *MoviesListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
MoviesListOKBody movies list o k body
swagger:model MoviesListOKBody
*/
type MoviesListOKBody struct {
	models.RequestPaginatedResponse

	// data
	Data []*models.APIMovieResponse `json:"data"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *MoviesListOKBody) UnmarshalJSON(raw []byte) error {
	// MoviesListOKBodyAO0
	var moviesListOKBodyAO0 models.RequestPaginatedResponse
	if err := swag.ReadJSON(raw, &moviesListOKBodyAO0); err != nil {
		return err
	}
	o.RequestPaginatedResponse = moviesListOKBodyAO0

	// MoviesListOKBodyAO1
	var dataMoviesListOKBodyAO1 struct {
		Data []*models.APIMovieResponse `json:"data"`
	}
	if err := swag.ReadJSON(raw, &dataMoviesListOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataMoviesListOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o MoviesListOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	moviesListOKBodyAO0, err := swag.WriteJSON(o.RequestPaginatedResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, moviesListOKBodyAO0)
	var dataMoviesListOKBodyAO1 struct {
		Data []*models.APIMovieResponse `json:"data"`
	}

	dataMoviesListOKBodyAO1.Data = o.Data

	jsonDataMoviesListOKBodyAO1, errMoviesListOKBodyAO1 := swag.WriteJSON(dataMoviesListOKBodyAO1)
	if errMoviesListOKBodyAO1 != nil {
		return nil, errMoviesListOKBodyAO1
	}
	_parts = append(_parts, jsonDataMoviesListOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this movies list o k body
func (o *MoviesListOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.RequestPaginatedResponse
	if err := o.RequestPaginatedResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *MoviesListOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("moviesListOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("moviesListOK" + "." + "data" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this movies list o k body based on the context it is used
func (o *MoviesListOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.RequestPaginatedResponse
	if err := o.RequestPaginatedResponse.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *MoviesListOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Data); i++ {

		if o.Data[i] != nil {

			if swag.IsZero(o.Data[i]) { // not required
				return nil
			}

			if err := o.Data[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("moviesListOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("moviesListOK" + "." + "data" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *MoviesListOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *MoviesListOKBody) UnmarshalBinary(b []byte) error {
	var res MoviesListOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
