// Code generated by go-swagger; DO NOT EDIT.

package timeslots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// TimeSlotsListReader is a Reader for the TimeSlotsList structure.
type TimeSlotsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TimeSlotsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewTimeSlotsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewTimeSlotsListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewTimeSlotsListNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewTimeSlotsListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots] TimeSlotsList", response, response.Code())
	}
}

// NewTimeSlotsListOK creates a TimeSlotsListOK with default headers values
func NewTimeSlotsListOK() *TimeSlotsListOK {
	return &TimeSlotsListOK{}
}

/*
TimeSlotsListOK describes a response with status code 200, with default header values.

OK
*/
type TimeSlotsListOK struct {
	Payload *TimeSlotsListOKBody
}

// IsSuccess returns true when this time slots list o k response has a 2xx status code
func (o *TimeSlotsListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this time slots list o k response has a 3xx status code
func (o *TimeSlotsListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this time slots list o k response has a 4xx status code
func (o *TimeSlotsListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this time slots list o k response has a 5xx status code
func (o *TimeSlotsListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this time slots list o k response a status code equal to that given
func (o *TimeSlotsListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the time slots list o k response
func (o *TimeSlotsListOK) Code() int {
	return 200
}

func (o *TimeSlotsListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots][%d] timeSlotsListOK %s", 200, payload)
}

func (o *TimeSlotsListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots][%d] timeSlotsListOK %s", 200, payload)
}

func (o *TimeSlotsListOK) GetPayload() *TimeSlotsListOKBody {
	return o.Payload
}

func (o *TimeSlotsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(TimeSlotsListOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTimeSlotsListBadRequest creates a TimeSlotsListBadRequest with default headers values
func NewTimeSlotsListBadRequest() *TimeSlotsListBadRequest {
	return &TimeSlotsListBadRequest{}
}

/*
TimeSlotsListBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type TimeSlotsListBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this time slots list bad request response has a 2xx status code
func (o *TimeSlotsListBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this time slots list bad request response has a 3xx status code
func (o *TimeSlotsListBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this time slots list bad request response has a 4xx status code
func (o *TimeSlotsListBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this time slots list bad request response has a 5xx status code
func (o *TimeSlotsListBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this time slots list bad request response a status code equal to that given
func (o *TimeSlotsListBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the time slots list bad request response
func (o *TimeSlotsListBadRequest) Code() int {
	return 400
}

func (o *TimeSlotsListBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots][%d] timeSlotsListBadRequest %s", 400, payload)
}

func (o *TimeSlotsListBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots][%d] timeSlotsListBadRequest %s", 400, payload)
}

func (o *TimeSlotsListBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TimeSlotsListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTimeSlotsListNotFound creates a TimeSlotsListNotFound with default headers values
func NewTimeSlotsListNotFound() *TimeSlotsListNotFound {
	return &TimeSlotsListNotFound{}
}

/*
TimeSlotsListNotFound describes a response with status code 404, with default header values.

Not Found
*/
type TimeSlotsListNotFound struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this time slots list not found response has a 2xx status code
func (o *TimeSlotsListNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this time slots list not found response has a 3xx status code
func (o *TimeSlotsListNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this time slots list not found response has a 4xx status code
func (o *TimeSlotsListNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this time slots list not found response has a 5xx status code
func (o *TimeSlotsListNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this time slots list not found response a status code equal to that given
func (o *TimeSlotsListNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the time slots list not found response
func (o *TimeSlotsListNotFound) Code() int {
	return 404
}

func (o *TimeSlotsListNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots][%d] timeSlotsListNotFound %s", 404, payload)
}

func (o *TimeSlotsListNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots][%d] timeSlotsListNotFound %s", 404, payload)
}

func (o *TimeSlotsListNotFound) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TimeSlotsListNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTimeSlotsListInternalServerError creates a TimeSlotsListInternalServerError with default headers values
func NewTimeSlotsListInternalServerError() *TimeSlotsListInternalServerError {
	return &TimeSlotsListInternalServerError{}
}

/*
TimeSlotsListInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type TimeSlotsListInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this time slots list internal server error response has a 2xx status code
func (o *TimeSlotsListInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this time slots list internal server error response has a 3xx status code
func (o *TimeSlotsListInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this time slots list internal server error response has a 4xx status code
func (o *TimeSlotsListInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this time slots list internal server error response has a 5xx status code
func (o *TimeSlotsListInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this time slots list internal server error response a status code equal to that given
func (o *TimeSlotsListInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the time slots list internal server error response
func (o *TimeSlotsListInternalServerError) Code() int {
	return 500
}

func (o *TimeSlotsListInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots][%d] timeSlotsListInternalServerError %s", 500, payload)
}

func (o *TimeSlotsListInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots][%d] timeSlotsListInternalServerError %s", 500, payload)
}

func (o *TimeSlotsListInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TimeSlotsListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
TimeSlotsListOKBody time slots list o k body
swagger:model TimeSlotsListOKBody
*/
type TimeSlotsListOKBody struct {
	models.RequestPaginatedResponse

	// data
	Data []*models.APITimeSlotResponse `json:"data"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *TimeSlotsListOKBody) UnmarshalJSON(raw []byte) error {
	// TimeSlotsListOKBodyAO0
	var timeSlotsListOKBodyAO0 models.RequestPaginatedResponse
	if err := swag.ReadJSON(raw, &timeSlotsListOKBodyAO0); err != nil {
		return err
	}
	o.RequestPaginatedResponse = timeSlotsListOKBodyAO0

	// TimeSlotsListOKBodyAO1
	var dataTimeSlotsListOKBodyAO1 struct {
		Data []*models.APITimeSlotResponse `json:"data"`
	}
	if err := swag.ReadJSON(raw, &dataTimeSlotsListOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataTimeSlotsListOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o TimeSlotsListOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	timeSlotsListOKBodyAO0, err := swag.WriteJSON(o.RequestPaginatedResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, timeSlotsListOKBodyAO0)
	var dataTimeSlotsListOKBodyAO1 struct {
		Data []*models.APITimeSlotResponse `json:"data"`
	}

	dataTimeSlotsListOKBodyAO1.Data = o.Data

	jsonDataTimeSlotsListOKBodyAO1, errTimeSlotsListOKBodyAO1 := swag.WriteJSON(dataTimeSlotsListOKBodyAO1)
	if errTimeSlotsListOKBodyAO1 != nil {
		return nil, errTimeSlotsListOKBodyAO1
	}
	_parts = append(_parts, jsonDataTimeSlotsListOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this time slots list o k body
func (o *TimeSlotsListOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.RequestPaginatedResponse
	if err := o.RequestPaginatedResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *TimeSlotsListOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("timeSlotsListOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("timeSlotsListOK" + "." + "data" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this time slots list o k body based on the context it is used
func (o *TimeSlotsListOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.RequestPaginatedResponse
	if err := o.RequestPaginatedResponse.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *TimeSlotsListOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Data); i++ {

		if o.Data[i] != nil {

			if swag.IsZero(o.Data[i]) { // not required
				return nil
			}

			if err := o.Data[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("timeSlotsListOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("timeSlotsListOK" + "." + "data" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *TimeSlotsListOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *TimeSlotsListOKBody) UnmarshalBinary(b []byte) error {
	var res TimeSlotsListOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
