// Code generated by go-swagger; DO NOT EDIT.

package timeslots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// TimeSlotsListReader is a Reader for the TimeSlotsList structure.
type TimeSlotsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TimeSlotsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewTimeSlotsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewTimeSlotsListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewTimeSlotsListNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewTimeSlotsListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots] TimeSlotsList", response, response.Code())
	}
}

// NewTimeSlotsListOK creates a TimeSlotsListOK with default headers values
func NewTimeSlotsListOK() *TimeSlotsListOK {
	return &TimeSlotsListOK{}
}

/*
TimeSlotsListOK describes a response with status code 200, with default header values.

OK
*/
type TimeSlotsListOK struct {
	Payload []*models.APITimeSlotResponse
}

// IsSuccess returns true when this time slots list o k response has a 2xx status code
func (o *TimeSlotsListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this time slots list o k response has a 3xx status code
func (o *TimeSlotsListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this time slots list o k response has a 4xx status code
func (o *TimeSlotsListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this time slots list o k response has a 5xx status code
func (o *TimeSlotsListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this time slots list o k response a status code equal to that given
func (o *TimeSlotsListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the time slots list o k response
func (o *TimeSlotsListOK) Code() int {
	return 200
}

func (o *TimeSlotsListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots][%d] timeSlotsListOK %s", 200, payload)
}

func (o *TimeSlotsListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots][%d] timeSlotsListOK %s", 200, payload)
}

func (o *TimeSlotsListOK) GetPayload() []*models.APITimeSlotResponse {
	return o.Payload
}

func (o *TimeSlotsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTimeSlotsListBadRequest creates a TimeSlotsListBadRequest with default headers values
func NewTimeSlotsListBadRequest() *TimeSlotsListBadRequest {
	return &TimeSlotsListBadRequest{}
}

/*
TimeSlotsListBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type TimeSlotsListBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this time slots list bad request response has a 2xx status code
func (o *TimeSlotsListBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this time slots list bad request response has a 3xx status code
func (o *TimeSlotsListBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this time slots list bad request response has a 4xx status code
func (o *TimeSlotsListBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this time slots list bad request response has a 5xx status code
func (o *TimeSlotsListBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this time slots list bad request response a status code equal to that given
func (o *TimeSlotsListBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the time slots list bad request response
func (o *TimeSlotsListBadRequest) Code() int {
	return 400
}

func (o *TimeSlotsListBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots][%d] timeSlotsListBadRequest %s", 400, payload)
}

func (o *TimeSlotsListBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots][%d] timeSlotsListBadRequest %s", 400, payload)
}

func (o *TimeSlotsListBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TimeSlotsListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTimeSlotsListNotFound creates a TimeSlotsListNotFound with default headers values
func NewTimeSlotsListNotFound() *TimeSlotsListNotFound {
	return &TimeSlotsListNotFound{}
}

/*
TimeSlotsListNotFound describes a response with status code 404, with default header values.

Not Found
*/
type TimeSlotsListNotFound struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this time slots list not found response has a 2xx status code
func (o *TimeSlotsListNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this time slots list not found response has a 3xx status code
func (o *TimeSlotsListNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this time slots list not found response has a 4xx status code
func (o *TimeSlotsListNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this time slots list not found response has a 5xx status code
func (o *TimeSlotsListNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this time slots list not found response a status code equal to that given
func (o *TimeSlotsListNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the time slots list not found response
func (o *TimeSlotsListNotFound) Code() int {
	return 404
}

func (o *TimeSlotsListNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots][%d] timeSlotsListNotFound %s", 404, payload)
}

func (o *TimeSlotsListNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots][%d] timeSlotsListNotFound %s", 404, payload)
}

func (o *TimeSlotsListNotFound) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TimeSlotsListNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTimeSlotsListInternalServerError creates a TimeSlotsListInternalServerError with default headers values
func NewTimeSlotsListInternalServerError() *TimeSlotsListInternalServerError {
	return &TimeSlotsListInternalServerError{}
}

/*
TimeSlotsListInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type TimeSlotsListInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this time slots list internal server error response has a 2xx status code
func (o *TimeSlotsListInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this time slots list internal server error response has a 3xx status code
func (o *TimeSlotsListInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this time slots list internal server error response has a 4xx status code
func (o *TimeSlotsListInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this time slots list internal server error response has a 5xx status code
func (o *TimeSlotsListInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this time slots list internal server error response a status code equal to that given
func (o *TimeSlotsListInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the time slots list internal server error response
func (o *TimeSlotsListInternalServerError) Code() int {
	return 500
}

func (o *TimeSlotsListInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots][%d] timeSlotsListInternalServerError %s", 500, payload)
}

func (o *TimeSlotsListInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots][%d] timeSlotsListInternalServerError %s", 500, payload)
}

func (o *TimeSlotsListInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TimeSlotsListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
