// Code generated by go-swagger; DO NOT EDIT.

package timeslots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// TimeSlotsShowReader is a Reader for the TimeSlotsShow structure.
type TimeSlotsShowReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TimeSlotsShowReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewTimeSlotsShowOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewTimeSlotsShowBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewTimeSlotsShowNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewTimeSlotsShowInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots/{timeSlotID}] TimeSlotsShow", response, response.Code())
	}
}

// NewTimeSlotsShowOK creates a TimeSlotsShowOK with default headers values
func NewTimeSlotsShowOK() *TimeSlotsShowOK {
	return &TimeSlotsShowOK{}
}

/*
TimeSlotsShowOK describes a response with status code 200, with default header values.

OK
*/
type TimeSlotsShowOK struct {
	Payload *models.APITimeSlotResponse
}

// IsSuccess returns true when this time slots show o k response has a 2xx status code
func (o *TimeSlotsShowOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this time slots show o k response has a 3xx status code
func (o *TimeSlotsShowOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this time slots show o k response has a 4xx status code
func (o *TimeSlotsShowOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this time slots show o k response has a 5xx status code
func (o *TimeSlotsShowOK) IsServerError() bool {
	return false
}

// IsCode returns true when this time slots show o k response a status code equal to that given
func (o *TimeSlotsShowOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the time slots show o k response
func (o *TimeSlotsShowOK) Code() int {
	return 200
}

func (o *TimeSlotsShowOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots/{timeSlotID}][%d] timeSlotsShowOK %s", 200, payload)
}

func (o *TimeSlotsShowOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots/{timeSlotID}][%d] timeSlotsShowOK %s", 200, payload)
}

func (o *TimeSlotsShowOK) GetPayload() *models.APITimeSlotResponse {
	return o.Payload
}

func (o *TimeSlotsShowOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APITimeSlotResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTimeSlotsShowBadRequest creates a TimeSlotsShowBadRequest with default headers values
func NewTimeSlotsShowBadRequest() *TimeSlotsShowBadRequest {
	return &TimeSlotsShowBadRequest{}
}

/*
TimeSlotsShowBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type TimeSlotsShowBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this time slots show bad request response has a 2xx status code
func (o *TimeSlotsShowBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this time slots show bad request response has a 3xx status code
func (o *TimeSlotsShowBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this time slots show bad request response has a 4xx status code
func (o *TimeSlotsShowBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this time slots show bad request response has a 5xx status code
func (o *TimeSlotsShowBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this time slots show bad request response a status code equal to that given
func (o *TimeSlotsShowBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the time slots show bad request response
func (o *TimeSlotsShowBadRequest) Code() int {
	return 400
}

func (o *TimeSlotsShowBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots/{timeSlotID}][%d] timeSlotsShowBadRequest %s", 400, payload)
}

func (o *TimeSlotsShowBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots/{timeSlotID}][%d] timeSlotsShowBadRequest %s", 400, payload)
}

func (o *TimeSlotsShowBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TimeSlotsShowBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTimeSlotsShowNotFound creates a TimeSlotsShowNotFound with default headers values
func NewTimeSlotsShowNotFound() *TimeSlotsShowNotFound {
	return &TimeSlotsShowNotFound{}
}

/*
TimeSlotsShowNotFound describes a response with status code 404, with default header values.

Not Found
*/
type TimeSlotsShowNotFound struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this time slots show not found response has a 2xx status code
func (o *TimeSlotsShowNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this time slots show not found response has a 3xx status code
func (o *TimeSlotsShowNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this time slots show not found response has a 4xx status code
func (o *TimeSlotsShowNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this time slots show not found response has a 5xx status code
func (o *TimeSlotsShowNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this time slots show not found response a status code equal to that given
func (o *TimeSlotsShowNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the time slots show not found response
func (o *TimeSlotsShowNotFound) Code() int {
	return 404
}

func (o *TimeSlotsShowNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots/{timeSlotID}][%d] timeSlotsShowNotFound %s", 404, payload)
}

func (o *TimeSlotsShowNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots/{timeSlotID}][%d] timeSlotsShowNotFound %s", 404, payload)
}

func (o *TimeSlotsShowNotFound) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TimeSlotsShowNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTimeSlotsShowInternalServerError creates a TimeSlotsShowInternalServerError with default headers values
func NewTimeSlotsShowInternalServerError() *TimeSlotsShowInternalServerError {
	return &TimeSlotsShowInternalServerError{}
}

/*
TimeSlotsShowInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type TimeSlotsShowInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this time slots show internal server error response has a 2xx status code
func (o *TimeSlotsShowInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this time slots show internal server error response has a 3xx status code
func (o *TimeSlotsShowInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this time slots show internal server error response has a 4xx status code
func (o *TimeSlotsShowInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this time slots show internal server error response has a 5xx status code
func (o *TimeSlotsShowInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this time slots show internal server error response a status code equal to that given
func (o *TimeSlotsShowInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the time slots show internal server error response
func (o *TimeSlotsShowInternalServerError) Code() int {
	return 500
}

func (o *TimeSlotsShowInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots/{timeSlotID}][%d] timeSlotsShowInternalServerError %s", 500, payload)
}

func (o *TimeSlotsShowInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}/timeslots/{timeSlotID}][%d] timeSlotsShowInternalServerError %s", 500, payload)
}

func (o *TimeSlotsShowInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TimeSlotsShowInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
