// Code generated by go-swagger; DO NOT EDIT.

package timeslots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewTimeSlotsShowParams creates a new TimeSlotsShowParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTimeSlotsShowParams() *TimeSlotsShowParams {
	return &TimeSlotsShowParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTimeSlotsShowParamsWithTimeout creates a new TimeSlotsShowParams object
// with the ability to set a timeout on a request.
func NewTimeSlotsShowParamsWithTimeout(timeout time.Duration) *TimeSlotsShowParams {
	return &TimeSlotsShowParams{
		timeout: timeout,
	}
}

// NewTimeSlotsShowParamsWithContext creates a new TimeSlotsShowParams object
// with the ability to set a context for a request.
func NewTimeSlotsShowParamsWithContext(ctx context.Context) *TimeSlotsShowParams {
	return &TimeSlotsShowParams{
		Context: ctx,
	}
}

// NewTimeSlotsShowParamsWithHTTPClient creates a new TimeSlotsShowParams object
// with the ability to set a custom HTTPClient for a request.
func NewTimeSlotsShowParamsWithHTTPClient(client *http.Client) *TimeSlotsShowParams {
	return &TimeSlotsShowParams{
		HTTPClient: client,
	}
}

/*
TimeSlotsShowParams contains all the parameters to send to the API endpoint

	for the time slots show operation.

	Typically these are written to a http.Request.
*/
type TimeSlotsShowParams struct {

	/* RoomID.

	   Room ID

	   Format: uuid
	*/
	RoomID strfmt.UUID

	/* TheaterID.

	   Theater ID

	   Format: uuid
	*/
	TheaterID strfmt.UUID

	/* TimeSlotID.

	   TimeSlot ID

	   Format: uuid
	*/
	TimeSlotID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the time slots show params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TimeSlotsShowParams) WithDefaults() *TimeSlotsShowParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the time slots show params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TimeSlotsShowParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the time slots show params
func (o *TimeSlotsShowParams) WithTimeout(timeout time.Duration) *TimeSlotsShowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the time slots show params
func (o *TimeSlotsShowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the time slots show params
func (o *TimeSlotsShowParams) WithContext(ctx context.Context) *TimeSlotsShowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the time slots show params
func (o *TimeSlotsShowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the time slots show params
func (o *TimeSlotsShowParams) WithHTTPClient(client *http.Client) *TimeSlotsShowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the time slots show params
func (o *TimeSlotsShowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRoomID adds the roomID to the time slots show params
func (o *TimeSlotsShowParams) WithRoomID(roomID strfmt.UUID) *TimeSlotsShowParams {
	o.SetRoomID(roomID)
	return o
}

// SetRoomID adds the roomId to the time slots show params
func (o *TimeSlotsShowParams) SetRoomID(roomID strfmt.UUID) {
	o.RoomID = roomID
}

// WithTheaterID adds the theaterID to the time slots show params
func (o *TimeSlotsShowParams) WithTheaterID(theaterID strfmt.UUID) *TimeSlotsShowParams {
	o.SetTheaterID(theaterID)
	return o
}

// SetTheaterID adds the theaterId to the time slots show params
func (o *TimeSlotsShowParams) SetTheaterID(theaterID strfmt.UUID) {
	o.TheaterID = theaterID
}

// WithTimeSlotID adds the timeSlotID to the time slots show params
func (o *TimeSlotsShowParams) WithTimeSlotID(timeSlotID strfmt.UUID) *TimeSlotsShowParams {
	o.SetTimeSlotID(timeSlotID)
	return o
}

// SetTimeSlotID adds the timeSlotId to the time slots show params
func (o *TimeSlotsShowParams) SetTimeSlotID(timeSlotID strfmt.UUID) {
	o.TimeSlotID = timeSlotID
}

// WriteToRequest writes these params to a swagger request
func (o *TimeSlotsShowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param roomID
	if err := r.SetPathParam("roomID", o.RoomID.String()); err != nil {
		return err
	}

	// path param theaterID
	if err := r.SetPathParam("theaterID", o.TheaterID.String()); err != nil {
		return err
	}

	// path param timeSlotID
	if err := r.SetPathParam("timeSlotID", o.TimeSlotID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
