// Code generated by go-swagger; DO NOT EDIT.

package timeslots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewTimeSlotsListParams creates a new TimeSlotsListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTimeSlotsListParams() *TimeSlotsListParams {
	return &TimeSlotsListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTimeSlotsListParamsWithTimeout creates a new TimeSlotsListParams object
// with the ability to set a timeout on a request.
func NewTimeSlotsListParamsWithTimeout(timeout time.Duration) *TimeSlotsListParams {
	return &TimeSlotsListParams{
		timeout: timeout,
	}
}

// NewTimeSlotsListParamsWithContext creates a new TimeSlotsListParams object
// with the ability to set a context for a request.
func NewTimeSlotsListParamsWithContext(ctx context.Context) *TimeSlotsListParams {
	return &TimeSlotsListParams{
		Context: ctx,
	}
}

// NewTimeSlotsListParamsWithHTTPClient creates a new TimeSlotsListParams object
// with the ability to set a custom HTTPClient for a request.
func NewTimeSlotsListParamsWithHTTPClient(client *http.Client) *TimeSlotsListParams {
	return &TimeSlotsListParams{
		HTTPClient: client,
	}
}

/*
TimeSlotsListParams contains all the parameters to send to the API endpoint

	for the time slots list operation.

	Typically these are written to a http.Request.
*/
type TimeSlotsListParams struct {

	/* Limit.

	   Limit the number of responses

	   Default: 10
	*/
	Limit *int64

	/* Offset.

	   Offset the first response
	*/
	Offset *int64

	/* RoomID.

	   Room ID

	   Format: uuid
	*/
	RoomID strfmt.UUID

	/* Sort.

	   Sort results
	*/
	Sort *string

	/* TheaterID.

	   Theater ID

	   Format: uuid
	*/
	TheaterID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the time slots list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TimeSlotsListParams) WithDefaults() *TimeSlotsListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the time slots list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TimeSlotsListParams) SetDefaults() {
	var (
		limitDefault = int64(10)

		offsetDefault = int64(0)
	)

	val := TimeSlotsListParams{
		Limit:  &limitDefault,
		Offset: &offsetDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the time slots list params
func (o *TimeSlotsListParams) WithTimeout(timeout time.Duration) *TimeSlotsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the time slots list params
func (o *TimeSlotsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the time slots list params
func (o *TimeSlotsListParams) WithContext(ctx context.Context) *TimeSlotsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the time slots list params
func (o *TimeSlotsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the time slots list params
func (o *TimeSlotsListParams) WithHTTPClient(client *http.Client) *TimeSlotsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the time slots list params
func (o *TimeSlotsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the time slots list params
func (o *TimeSlotsListParams) WithLimit(limit *int64) *TimeSlotsListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the time slots list params
func (o *TimeSlotsListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the time slots list params
func (o *TimeSlotsListParams) WithOffset(offset *int64) *TimeSlotsListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the time slots list params
func (o *TimeSlotsListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithRoomID adds the roomID to the time slots list params
func (o *TimeSlotsListParams) WithRoomID(roomID strfmt.UUID) *TimeSlotsListParams {
	o.SetRoomID(roomID)
	return o
}

// SetRoomID adds the roomId to the time slots list params
func (o *TimeSlotsListParams) SetRoomID(roomID strfmt.UUID) {
	o.RoomID = roomID
}

// WithSort adds the sort to the time slots list params
func (o *TimeSlotsListParams) WithSort(sort *string) *TimeSlotsListParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the time slots list params
func (o *TimeSlotsListParams) SetSort(sort *string) {
	o.Sort = sort
}

// WithTheaterID adds the theaterID to the time slots list params
func (o *TimeSlotsListParams) WithTheaterID(theaterID strfmt.UUID) *TimeSlotsListParams {
	o.SetTheaterID(theaterID)
	return o
}

// SetTheaterID adds the theaterId to the time slots list params
func (o *TimeSlotsListParams) SetTheaterID(theaterID strfmt.UUID) {
	o.TheaterID = theaterID
}

// WriteToRequest writes these params to a swagger request
func (o *TimeSlotsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	// path param roomID
	if err := r.SetPathParam("roomID", o.RoomID.String()); err != nil {
		return err
	}

	if o.Sort != nil {

		// query param sort
		var qrSort string

		if o.Sort != nil {
			qrSort = *o.Sort
		}
		qSort := qrSort
		if qSort != "" {

			if err := r.SetQueryParam("sort", qSort); err != nil {
				return err
			}
		}
	}

	// path param theaterID
	if err := r.SetPathParam("theaterID", o.TheaterID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
