// Code generated by go-swagger; DO NOT EDIT.

package timeslots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new timeslots API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new timeslots API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new timeslots API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for timeslots API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	TimeSlotsList(params *TimeSlotsListParams, opts ...ClientOption) (*TimeSlotsListOK, error)

	TimeSlotsShow(params *TimeSlotsShowParams, opts ...ClientOption) (*TimeSlotsShowOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
TimeSlotsList lists time slots

List time slots
*/
func (a *Client) TimeSlotsList(params *TimeSlotsListParams, opts ...ClientOption) (*TimeSlotsListOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewTimeSlotsListParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "TimeSlotsList",
		Method:             "GET",
		PathPattern:        "/theaters/{theaterID}/rooms/{roomID}/timeslots",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &TimeSlotsListReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*TimeSlotsListOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for TimeSlotsList: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
TimeSlotsShow shows time slot

Show time slot
*/
func (a *Client) TimeSlotsShow(params *TimeSlotsShowParams, opts ...ClientOption) (*TimeSlotsShowOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewTimeSlotsShowParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "TimeSlotsShow",
		Method:             "GET",
		PathPattern:        "/theaters/{theaterID}/rooms/{roomID}/timeslots/{timeSlotID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &TimeSlotsShowReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*TimeSlotsShowOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for TimeSlotsShow: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
