// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIMovieResponse api movie response
//
// swagger:model api.MovieResponse
type APIMovieResponse struct {

	// active
	Active bool `json:"active,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// image url
	ImageURL string `json:"image_url,omitempty"`

	// length minutes
	LengthMinutes int64 `json:"length_minutes,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// rating
	Rating float64 `json:"rating,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`
}

// Validate validates this api movie response
func (m *APIMovieResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api movie response based on context it is used
func (m *APIMovieResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIMovieResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIMovieResponse) UnmarshalBinary(b []byte) error {
	var res APIMovieResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
