// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APITimeSlotResponse api time slot response
//
// swagger:model api.TimeSlotResponse
type APITimeSlotResponse struct {

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// end time
	EndTime string `json:"end_time,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// movie id
	MovieID string `json:"movie_id,omitempty"`

	// room id
	RoomID string `json:"room_id,omitempty"`

	// start time
	StartTime string `json:"start_time,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`
}

// Validate validates this api time slot response
func (m *APITimeSlotResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api time slot response based on context it is used
func (m *APITimeSlotResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APITimeSlotResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APITimeSlotResponse) UnmarshalBinary(b []byte) error {
	var res APITimeSlotResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
