// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIRoomRequest api room request
//
// swagger:model api.RoomRequest
type APIRoomRequest struct {

	// closing hour
	// Required: true
	// Maximum: 24
	// Minimum: 0
	ClosingHour *int64 `json:"closing_hour"`

	// columns
	// Required: true
	// Maximum: 100
	// Minimum: 1
	Columns *int64 `json:"columns"`

	// name
	// Required: true
	// Min Length: 3
	Name *string `json:"name"`

	// opening hour
	// Required: true
	// Maximum: 24
	// Minimum: 0
	OpeningHour *int64 `json:"opening_hour"`

	// operating mode
	// Required: true
	// Enum: ["CLOSED","WEEKDAYS","WEEKENDS","ALL"]
	OperatingMode *string `json:"operating_mode"`

	// rows
	// Required: true
	// Maximum: 100
	// Minimum: 1
	Rows *int64 `json:"rows"`
}

// Validate validates this api room request
func (m *APIRoomRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClosingHour(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateColumns(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOpeningHour(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOperatingMode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRows(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIRoomRequest) validateClosingHour(formats strfmt.Registry) error {

	if err := validate.Required("closing_hour", "body", m.ClosingHour); err != nil {
		return err
	}

	if err := validate.MinimumInt("closing_hour", "body", *m.ClosingHour, 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("closing_hour", "body", *m.ClosingHour, 24, false); err != nil {
		return err
	}

	return nil
}

func (m *APIRoomRequest) validateColumns(formats strfmt.Registry) error {

	if err := validate.Required("columns", "body", m.Columns); err != nil {
		return err
	}

	if err := validate.MinimumInt("columns", "body", *m.Columns, 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("columns", "body", *m.Columns, 100, false); err != nil {
		return err
	}

	return nil
}

func (m *APIRoomRequest) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", *m.Name, 3); err != nil {
		return err
	}

	return nil
}

func (m *APIRoomRequest) validateOpeningHour(formats strfmt.Registry) error {

	if err := validate.Required("opening_hour", "body", m.OpeningHour); err != nil {
		return err
	}

	if err := validate.MinimumInt("opening_hour", "body", *m.OpeningHour, 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("opening_hour", "body", *m.OpeningHour, 24, false); err != nil {
		return err
	}

	return nil
}

var apiRoomRequestTypeOperatingModePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["CLOSED","WEEKDAYS","WEEKENDS","ALL"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		apiRoomRequestTypeOperatingModePropEnum = append(apiRoomRequestTypeOperatingModePropEnum, v)
	}
}

const (

	// APIRoomRequestOperatingModeCLOSED captures enum value "CLOSED"
	APIRoomRequestOperatingModeCLOSED string = "CLOSED"

	// APIRoomRequestOperatingModeWEEKDAYS captures enum value "WEEKDAYS"
	APIRoomRequestOperatingModeWEEKDAYS string = "WEEKDAYS"

	// APIRoomRequestOperatingModeWEEKENDS captures enum value "WEEKENDS"
	APIRoomRequestOperatingModeWEEKENDS string = "WEEKENDS"

	// APIRoomRequestOperatingModeALL captures enum value "ALL"
	APIRoomRequestOperatingModeALL string = "ALL"
)

// prop value enum
func (m *APIRoomRequest) validateOperatingModeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, apiRoomRequestTypeOperatingModePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *APIRoomRequest) validateOperatingMode(formats strfmt.Registry) error {

	if err := validate.Required("operating_mode", "body", m.OperatingMode); err != nil {
		return err
	}

	// value enum
	if err := m.validateOperatingModeEnum("operating_mode", "body", *m.OperatingMode); err != nil {
		return err
	}

	return nil
}

func (m *APIRoomRequest) validateRows(formats strfmt.Registry) error {

	if err := validate.Required("rows", "body", m.Rows); err != nil {
		return err
	}

	if err := validate.MinimumInt("rows", "body", *m.Rows, 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("rows", "body", *m.Rows, 100, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this api room request based on context it is used
func (m *APIRoomRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIRoomRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIRoomRequest) UnmarshalBinary(b []byte) error {
	var res APIRoomRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
