// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIRoomResponse api room response
//
// swagger:model api.RoomResponse
type APIRoomResponse struct {

	// closing hour
	ClosingHour int64 `json:"closing_hour,omitempty"`

	// columns
	Columns int64 `json:"columns,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// opening hour
	OpeningHour int64 `json:"opening_hour,omitempty"`

	// operating mode
	OperatingMode ModelsRoomOperatingMode `json:"operating_mode,omitempty"`

	// rows
	Rows int64 `json:"rows,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`
}

// Validate validates this api room response
func (m *APIRoomResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOperatingMode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIRoomResponse) validateOperatingMode(formats strfmt.Registry) error {
	if swag.IsZero(m.OperatingMode) { // not required
		return nil
	}

	if err := m.OperatingMode.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("operating_mode")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("operating_mode")
		}

		return err
	}

	return nil
}

// ContextValidate validate this api room response based on the context it is used
func (m *APIRoomResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateOperatingMode(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIRoomResponse) contextValidateOperatingMode(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.OperatingMode) { // not required
		return nil
	}

	if err := m.OperatingMode.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("operating_mode")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("operating_mode")
		}

		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIRoomResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIRoomResponse) UnmarshalBinary(b []byte) error {
	var res APIRoomResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
