// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIMovieRequest api movie request
//
// swagger:model api.MovieRequest
type APIMovieRequest struct {

	// active
	Active bool `json:"active,omitempty"`

	// description
	// Required: true
	// Min Length: 10
	Description *string `json:"description"`

	// image url
	// Required: true
	ImageURL *string `json:"image_url"`

	// length minutes
	// Required: true
	// Maximum: 1000
	// Minimum: 10
	LengthMinutes *int64 `json:"length_minutes"`

	// rating
	// Required: true
	// Maximum: 10
	// Minimum: 0
	Rating *float64 `json:"rating"`

	// title
	// Required: true
	// Min Length: 3
	Title *string `json:"title"`
}

// Validate validates this api movie request
func (m *APIMovieRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateImageURL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLengthMinutes(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRating(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTitle(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIMovieRequest) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", m.Description); err != nil {
		return err
	}

	if err := validate.MinLength("description", "body", *m.Description, 10); err != nil {
		return err
	}

	return nil
}

func (m *APIMovieRequest) validateImageURL(formats strfmt.Registry) error {

	if err := validate.Required("image_url", "body", m.ImageURL); err != nil {
		return err
	}

	return nil
}

func (m *APIMovieRequest) validateLengthMinutes(formats strfmt.Registry) error {

	if err := validate.Required("length_minutes", "body", m.LengthMinutes); err != nil {
		return err
	}

	if err := validate.MinimumInt("length_minutes", "body", *m.LengthMinutes, 10, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("length_minutes", "body", *m.LengthMinutes, 1000, false); err != nil {
		return err
	}

	return nil
}

func (m *APIMovieRequest) validateRating(formats strfmt.Registry) error {

	if err := validate.Required("rating", "body", m.Rating); err != nil {
		return err
	}

	if err := validate.Minimum("rating", "body", *m.Rating, 0, false); err != nil {
		return err
	}

	if err := validate.Maximum("rating", "body", *m.Rating, 10, false); err != nil {
		return err
	}

	return nil
}

func (m *APIMovieRequest) validateTitle(formats strfmt.Registry) error {

	if err := validate.Required("title", "body", m.Title); err != nil {
		return err
	}

	if err := validate.MinLength("title", "body", *m.Title, 3); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this api movie request based on context it is used
func (m *APIMovieRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIMovieRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIMovieRequest) UnmarshalBinary(b []byte) error {
	var res APIMovieRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
