// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MiddlewareHTTPError middleware Http error
//
// swagger:model middleware.HttpError
type MiddlewareHTTPError struct {

	// code
	Code int64 `json:"code,omitempty"`

	// fields
	Fields map[string]string `json:"fields,omitempty"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this middleware Http error
func (m *MiddlewareHTTPError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this middleware Http error based on context it is used
func (m *MiddlewareHTTPError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MiddlewareHTTPError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MiddlewareHTTPError) UnmarshalBinary(b []byte) error {
	var res MiddlewareHTTPError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
