// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ModelsRoomOperatingMode models room operating mode
//
// swagger:model models.RoomOperatingMode
type ModelsRoomOperatingMode string

func NewModelsRoomOperatingMode(value ModelsRoomOperatingMode) *ModelsRoomOperatingMode {
	return &value
}

// Pointer returns a pointer to a freshly-allocated ModelsRoomOperatingMode.
func (m ModelsRoomOperatingMode) Pointer() *ModelsRoomOperatingMode {
	return &m
}

const (

	// ModelsRoomOperatingModeCLOSED captures enum value "CLOSED"
	ModelsRoomOperatingModeCLOSED ModelsRoomOperatingMode = "CLOSED"

	// ModelsRoomOperatingModeWEEKDAYS captures enum value "WEEKDAYS"
	ModelsRoomOperatingModeWEEKDAYS ModelsRoomOperatingMode = "WEEKDAYS"

	// ModelsRoomOperatingModeWEEKENDS captures enum value "WEEKENDS"
	ModelsRoomOperatingModeWEEKENDS ModelsRoomOperatingMode = "WEEKENDS"

	// ModelsRoomOperatingModeALL captures enum value "ALL"
	ModelsRoomOperatingModeALL ModelsRoomOperatingMode = "ALL"
)

// for schema
var modelsRoomOperatingModeEnum []any

func init() {
	var res []ModelsRoomOperatingMode
	if err := json.Unmarshal([]byte(`["CLOSED","WEEKDAYS","WEEKENDS","ALL"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		modelsRoomOperatingModeEnum = append(modelsRoomOperatingModeEnum, v)
	}
}

func (m ModelsRoomOperatingMode) validateModelsRoomOperatingModeEnum(path, location string, value ModelsRoomOperatingMode) error {
	if err := validate.EnumCase(path, location, value, modelsRoomOperatingModeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this models room operating mode
func (m ModelsRoomOperatingMode) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateModelsRoomOperatingModeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this models room operating mode based on context it is used
func (m ModelsRoomOperatingMode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
