// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RequestPaginatedResponse request paginated response
//
// swagger:model request.PaginatedResponse
type RequestPaginatedResponse struct {

	// data
	Data any `json:"data,omitempty"`

	// limit
	Limit int64 `json:"limit,omitempty"`

	// offset
	Offset int64 `json:"offset,omitempty"`

	// total
	Total int64 `json:"total,omitempty"`
}

// Validate validates this request paginated response
func (m *RequestPaginatedResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this request paginated response based on context it is used
func (m *RequestPaginatedResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestPaginatedResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestPaginatedResponse) UnmarshalBinary(b []byte) error {
	var res RequestPaginatedResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
