// Code generated by go-swagger; DO NOT EDIT.

package rooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// NewRoomsUpdateParams creates a new RoomsUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRoomsUpdateParams() *RoomsUpdateParams {
	return &RoomsUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRoomsUpdateParamsWithTimeout creates a new RoomsUpdateParams object
// with the ability to set a timeout on a request.
func NewRoomsUpdateParamsWithTimeout(timeout time.Duration) *RoomsUpdateParams {
	return &RoomsUpdateParams{
		timeout: timeout,
	}
}

// NewRoomsUpdateParamsWithContext creates a new RoomsUpdateParams object
// with the ability to set a context for a request.
func NewRoomsUpdateParamsWithContext(ctx context.Context) *RoomsUpdateParams {
	return &RoomsUpdateParams{
		Context: ctx,
	}
}

// NewRoomsUpdateParamsWithHTTPClient creates a new RoomsUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewRoomsUpdateParamsWithHTTPClient(client *http.Client) *RoomsUpdateParams {
	return &RoomsUpdateParams{
		HTTPClient: client,
	}
}

/*
RoomsUpdateParams contains all the parameters to send to the API endpoint

	for the rooms update operation.

	Typically these are written to a http.Request.
*/
type RoomsUpdateParams struct {

	/* Request.

	   request body
	*/
	Request *models.APIRoomRequest

	/* RoomID.

	   Room ID

	   Format: uuid
	*/
	RoomID strfmt.UUID

	/* TheaterID.

	   Theater ID

	   Format: uuid
	*/
	TheaterID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the rooms update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RoomsUpdateParams) WithDefaults() *RoomsUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the rooms update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RoomsUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the rooms update params
func (o *RoomsUpdateParams) WithTimeout(timeout time.Duration) *RoomsUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rooms update params
func (o *RoomsUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rooms update params
func (o *RoomsUpdateParams) WithContext(ctx context.Context) *RoomsUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rooms update params
func (o *RoomsUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rooms update params
func (o *RoomsUpdateParams) WithHTTPClient(client *http.Client) *RoomsUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rooms update params
func (o *RoomsUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the rooms update params
func (o *RoomsUpdateParams) WithRequest(request *models.APIRoomRequest) *RoomsUpdateParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the rooms update params
func (o *RoomsUpdateParams) SetRequest(request *models.APIRoomRequest) {
	o.Request = request
}

// WithRoomID adds the roomID to the rooms update params
func (o *RoomsUpdateParams) WithRoomID(roomID strfmt.UUID) *RoomsUpdateParams {
	o.SetRoomID(roomID)
	return o
}

// SetRoomID adds the roomId to the rooms update params
func (o *RoomsUpdateParams) SetRoomID(roomID strfmt.UUID) {
	o.RoomID = roomID
}

// WithTheaterID adds the theaterID to the rooms update params
func (o *RoomsUpdateParams) WithTheaterID(theaterID strfmt.UUID) *RoomsUpdateParams {
	o.SetTheaterID(theaterID)
	return o
}

// SetTheaterID adds the theaterId to the rooms update params
func (o *RoomsUpdateParams) SetTheaterID(theaterID strfmt.UUID) {
	o.TheaterID = theaterID
}

// WriteToRequest writes these params to a swagger request
func (o *RoomsUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// path param roomID
	if err := r.SetPathParam("roomID", o.RoomID.String()); err != nil {
		return err
	}

	// path param theaterID
	if err := r.SetPathParam("theaterID", o.TheaterID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
