// Code generated by go-swagger; DO NOT EDIT.

package rooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewRoomsListParams creates a new RoomsListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRoomsListParams() *RoomsListParams {
	return &RoomsListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRoomsListParamsWithTimeout creates a new RoomsListParams object
// with the ability to set a timeout on a request.
func NewRoomsListParamsWithTimeout(timeout time.Duration) *RoomsListParams {
	return &RoomsListParams{
		timeout: timeout,
	}
}

// NewRoomsListParamsWithContext creates a new RoomsListParams object
// with the ability to set a context for a request.
func NewRoomsListParamsWithContext(ctx context.Context) *RoomsListParams {
	return &RoomsListParams{
		Context: ctx,
	}
}

// NewRoomsListParamsWithHTTPClient creates a new RoomsListParams object
// with the ability to set a custom HTTPClient for a request.
func NewRoomsListParamsWithHTTPClient(client *http.Client) *RoomsListParams {
	return &RoomsListParams{
		HTTPClient: client,
	}
}

/*
RoomsListParams contains all the parameters to send to the API endpoint

	for the rooms list operation.

	Typically these are written to a http.Request.
*/
type RoomsListParams struct {

	/* Limit.

	   Limit the number of responses

	   Default: 10
	*/
	Limit *int64

	/* Offset.

	   Offset the first response
	*/
	Offset *int64

	/* Sort.

	   Sort results
	*/
	Sort *string

	/* TheaterID.

	   Theater ID

	   Format: uuid
	*/
	TheaterID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the rooms list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RoomsListParams) WithDefaults() *RoomsListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the rooms list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RoomsListParams) SetDefaults() {
	var (
		limitDefault = int64(10)

		offsetDefault = int64(0)
	)

	val := RoomsListParams{
		Limit:  &limitDefault,
		Offset: &offsetDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the rooms list params
func (o *RoomsListParams) WithTimeout(timeout time.Duration) *RoomsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rooms list params
func (o *RoomsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rooms list params
func (o *RoomsListParams) WithContext(ctx context.Context) *RoomsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rooms list params
func (o *RoomsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rooms list params
func (o *RoomsListParams) WithHTTPClient(client *http.Client) *RoomsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rooms list params
func (o *RoomsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the rooms list params
func (o *RoomsListParams) WithLimit(limit *int64) *RoomsListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the rooms list params
func (o *RoomsListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the rooms list params
func (o *RoomsListParams) WithOffset(offset *int64) *RoomsListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the rooms list params
func (o *RoomsListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithSort adds the sort to the rooms list params
func (o *RoomsListParams) WithSort(sort *string) *RoomsListParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the rooms list params
func (o *RoomsListParams) SetSort(sort *string) {
	o.Sort = sort
}

// WithTheaterID adds the theaterID to the rooms list params
func (o *RoomsListParams) WithTheaterID(theaterID strfmt.UUID) *RoomsListParams {
	o.SetTheaterID(theaterID)
	return o
}

// SetTheaterID adds the theaterId to the rooms list params
func (o *RoomsListParams) SetTheaterID(theaterID strfmt.UUID) {
	o.TheaterID = theaterID
}

// WriteToRequest writes these params to a swagger request
func (o *RoomsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.Sort != nil {

		// query param sort
		var qrSort string

		if o.Sort != nil {
			qrSort = *o.Sort
		}
		qSort := qrSort
		if qSort != "" {

			if err := r.SetQueryParam("sort", qSort); err != nil {
				return err
			}
		}
	}

	// path param theaterID
	if err := r.SetPathParam("theaterID", o.TheaterID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
