// Code generated by go-swagger; DO NOT EDIT.

package rooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// RoomsListReader is a Reader for the RoomsList structure.
type RoomsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RoomsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewRoomsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRoomsListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRoomsListNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRoomsListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /theaters/{theaterID}/rooms] RoomsList", response, response.Code())
	}
}

// NewRoomsListOK creates a RoomsListOK with default headers values
func NewRoomsListOK() *RoomsListOK {
	return &RoomsListOK{}
}

/*
RoomsListOK describes a response with status code 200, with default header values.

OK
*/
type RoomsListOK struct {
	Payload []*models.APIRoomResponse
}

// IsSuccess returns true when this rooms list o k response has a 2xx status code
func (o *RoomsListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this rooms list o k response has a 3xx status code
func (o *RoomsListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms list o k response has a 4xx status code
func (o *RoomsListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this rooms list o k response has a 5xx status code
func (o *RoomsListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this rooms list o k response a status code equal to that given
func (o *RoomsListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the rooms list o k response
func (o *RoomsListOK) Code() int {
	return 200
}

func (o *RoomsListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms][%d] roomsListOK %s", 200, payload)
}

func (o *RoomsListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms][%d] roomsListOK %s", 200, payload)
}

func (o *RoomsListOK) GetPayload() []*models.APIRoomResponse {
	return o.Payload
}

func (o *RoomsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRoomsListBadRequest creates a RoomsListBadRequest with default headers values
func NewRoomsListBadRequest() *RoomsListBadRequest {
	return &RoomsListBadRequest{}
}

/*
RoomsListBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type RoomsListBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this rooms list bad request response has a 2xx status code
func (o *RoomsListBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this rooms list bad request response has a 3xx status code
func (o *RoomsListBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms list bad request response has a 4xx status code
func (o *RoomsListBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this rooms list bad request response has a 5xx status code
func (o *RoomsListBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this rooms list bad request response a status code equal to that given
func (o *RoomsListBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the rooms list bad request response
func (o *RoomsListBadRequest) Code() int {
	return 400
}

func (o *RoomsListBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms][%d] roomsListBadRequest %s", 400, payload)
}

func (o *RoomsListBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms][%d] roomsListBadRequest %s", 400, payload)
}

func (o *RoomsListBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RoomsListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRoomsListNotFound creates a RoomsListNotFound with default headers values
func NewRoomsListNotFound() *RoomsListNotFound {
	return &RoomsListNotFound{}
}

/*
RoomsListNotFound describes a response with status code 404, with default header values.

Not Found
*/
type RoomsListNotFound struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this rooms list not found response has a 2xx status code
func (o *RoomsListNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this rooms list not found response has a 3xx status code
func (o *RoomsListNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms list not found response has a 4xx status code
func (o *RoomsListNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this rooms list not found response has a 5xx status code
func (o *RoomsListNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this rooms list not found response a status code equal to that given
func (o *RoomsListNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the rooms list not found response
func (o *RoomsListNotFound) Code() int {
	return 404
}

func (o *RoomsListNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms][%d] roomsListNotFound %s", 404, payload)
}

func (o *RoomsListNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms][%d] roomsListNotFound %s", 404, payload)
}

func (o *RoomsListNotFound) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RoomsListNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRoomsListInternalServerError creates a RoomsListInternalServerError with default headers values
func NewRoomsListInternalServerError() *RoomsListInternalServerError {
	return &RoomsListInternalServerError{}
}

/*
RoomsListInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type RoomsListInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this rooms list internal server error response has a 2xx status code
func (o *RoomsListInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this rooms list internal server error response has a 3xx status code
func (o *RoomsListInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms list internal server error response has a 4xx status code
func (o *RoomsListInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this rooms list internal server error response has a 5xx status code
func (o *RoomsListInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this rooms list internal server error response a status code equal to that given
func (o *RoomsListInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the rooms list internal server error response
func (o *RoomsListInternalServerError) Code() int {
	return 500
}

func (o *RoomsListInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms][%d] roomsListInternalServerError %s", 500, payload)
}

func (o *RoomsListInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms][%d] roomsListInternalServerError %s", 500, payload)
}

func (o *RoomsListInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RoomsListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
