// Code generated by go-swagger; DO NOT EDIT.

package rooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// RoomsListReader is a Reader for the RoomsList structure.
type RoomsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RoomsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewRoomsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRoomsListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRoomsListNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRoomsListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /theaters/{theaterID}/rooms] RoomsList", response, response.Code())
	}
}

// NewRoomsListOK creates a RoomsListOK with default headers values
func NewRoomsListOK() *RoomsListOK {
	return &RoomsListOK{}
}

/*
RoomsListOK describes a response with status code 200, with default header values.

OK
*/
type RoomsListOK struct {
	Payload *RoomsListOKBody
}

// IsSuccess returns true when this rooms list o k response has a 2xx status code
func (o *RoomsListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this rooms list o k response has a 3xx status code
func (o *RoomsListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms list o k response has a 4xx status code
func (o *RoomsListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this rooms list o k response has a 5xx status code
func (o *RoomsListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this rooms list o k response a status code equal to that given
func (o *RoomsListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the rooms list o k response
func (o *RoomsListOK) Code() int {
	return 200
}

func (o *RoomsListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms][%d] roomsListOK %s", 200, payload)
}

func (o *RoomsListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms][%d] roomsListOK %s", 200, payload)
}

func (o *RoomsListOK) GetPayload() *RoomsListOKBody {
	return o.Payload
}

func (o *RoomsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(RoomsListOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRoomsListBadRequest creates a RoomsListBadRequest with default headers values
func NewRoomsListBadRequest() *RoomsListBadRequest {
	return &RoomsListBadRequest{}
}

/*
RoomsListBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type RoomsListBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this rooms list bad request response has a 2xx status code
func (o *RoomsListBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this rooms list bad request response has a 3xx status code
func (o *RoomsListBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms list bad request response has a 4xx status code
func (o *RoomsListBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this rooms list bad request response has a 5xx status code
func (o *RoomsListBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this rooms list bad request response a status code equal to that given
func (o *RoomsListBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the rooms list bad request response
func (o *RoomsListBadRequest) Code() int {
	return 400
}

func (o *RoomsListBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms][%d] roomsListBadRequest %s", 400, payload)
}

func (o *RoomsListBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms][%d] roomsListBadRequest %s", 400, payload)
}

func (o *RoomsListBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RoomsListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRoomsListNotFound creates a RoomsListNotFound with default headers values
func NewRoomsListNotFound() *RoomsListNotFound {
	return &RoomsListNotFound{}
}

/*
RoomsListNotFound describes a response with status code 404, with default header values.

Not Found
*/
type RoomsListNotFound struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this rooms list not found response has a 2xx status code
func (o *RoomsListNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this rooms list not found response has a 3xx status code
func (o *RoomsListNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms list not found response has a 4xx status code
func (o *RoomsListNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this rooms list not found response has a 5xx status code
func (o *RoomsListNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this rooms list not found response a status code equal to that given
func (o *RoomsListNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the rooms list not found response
func (o *RoomsListNotFound) Code() int {
	return 404
}

func (o *RoomsListNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms][%d] roomsListNotFound %s", 404, payload)
}

func (o *RoomsListNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms][%d] roomsListNotFound %s", 404, payload)
}

func (o *RoomsListNotFound) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RoomsListNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRoomsListInternalServerError creates a RoomsListInternalServerError with default headers values
func NewRoomsListInternalServerError() *RoomsListInternalServerError {
	return &RoomsListInternalServerError{}
}

/*
RoomsListInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type RoomsListInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this rooms list internal server error response has a 2xx status code
func (o *RoomsListInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this rooms list internal server error response has a 3xx status code
func (o *RoomsListInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms list internal server error response has a 4xx status code
func (o *RoomsListInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this rooms list internal server error response has a 5xx status code
func (o *RoomsListInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this rooms list internal server error response a status code equal to that given
func (o *RoomsListInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the rooms list internal server error response
func (o *RoomsListInternalServerError) Code() int {
	return 500
}

func (o *RoomsListInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms][%d] roomsListInternalServerError %s", 500, payload)
}

func (o *RoomsListInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms][%d] roomsListInternalServerError %s", 500, payload)
}

func (o *RoomsListInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RoomsListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
RoomsListOKBody rooms list o k body
swagger:model RoomsListOKBody
*/
type RoomsListOKBody struct {
	models.RequestPaginatedResponse

	// data
	Data []*models.APIRoomResponse `json:"data"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *RoomsListOKBody) UnmarshalJSON(raw []byte) error {
	// RoomsListOKBodyAO0
	var roomsListOKBodyAO0 models.RequestPaginatedResponse
	if err := swag.ReadJSON(raw, &roomsListOKBodyAO0); err != nil {
		return err
	}
	o.RequestPaginatedResponse = roomsListOKBodyAO0

	// RoomsListOKBodyAO1
	var dataRoomsListOKBodyAO1 struct {
		Data []*models.APIRoomResponse `json:"data"`
	}
	if err := swag.ReadJSON(raw, &dataRoomsListOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataRoomsListOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o RoomsListOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	roomsListOKBodyAO0, err := swag.WriteJSON(o.RequestPaginatedResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, roomsListOKBodyAO0)
	var dataRoomsListOKBodyAO1 struct {
		Data []*models.APIRoomResponse `json:"data"`
	}

	dataRoomsListOKBodyAO1.Data = o.Data

	jsonDataRoomsListOKBodyAO1, errRoomsListOKBodyAO1 := swag.WriteJSON(dataRoomsListOKBodyAO1)
	if errRoomsListOKBodyAO1 != nil {
		return nil, errRoomsListOKBodyAO1
	}
	_parts = append(_parts, jsonDataRoomsListOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this rooms list o k body
func (o *RoomsListOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.RequestPaginatedResponse
	if err := o.RequestPaginatedResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RoomsListOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("roomsListOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("roomsListOK" + "." + "data" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this rooms list o k body based on the context it is used
func (o *RoomsListOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.RequestPaginatedResponse
	if err := o.RequestPaginatedResponse.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RoomsListOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Data); i++ {

		if o.Data[i] != nil {

			if swag.IsZero(o.Data[i]) { // not required
				return nil
			}

			if err := o.Data[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("roomsListOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("roomsListOK" + "." + "data" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *RoomsListOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RoomsListOKBody) UnmarshalBinary(b []byte) error {
	var res RoomsListOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
