// Code generated by go-swagger; DO NOT EDIT.

package rooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRoomsShowParams creates a new RoomsShowParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRoomsShowParams() *RoomsShowParams {
	return &RoomsShowParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRoomsShowParamsWithTimeout creates a new RoomsShowParams object
// with the ability to set a timeout on a request.
func NewRoomsShowParamsWithTimeout(timeout time.Duration) *RoomsShowParams {
	return &RoomsShowParams{
		timeout: timeout,
	}
}

// NewRoomsShowParamsWithContext creates a new RoomsShowParams object
// with the ability to set a context for a request.
func NewRoomsShowParamsWithContext(ctx context.Context) *RoomsShowParams {
	return &RoomsShowParams{
		Context: ctx,
	}
}

// NewRoomsShowParamsWithHTTPClient creates a new RoomsShowParams object
// with the ability to set a custom HTTPClient for a request.
func NewRoomsShowParamsWithHTTPClient(client *http.Client) *RoomsShowParams {
	return &RoomsShowParams{
		HTTPClient: client,
	}
}

/*
RoomsShowParams contains all the parameters to send to the API endpoint

	for the rooms show operation.

	Typically these are written to a http.Request.
*/
type RoomsShowParams struct {

	/* RoomID.

	   Room ID

	   Format: uuid
	*/
	RoomID strfmt.UUID

	/* TheaterID.

	   Theater ID

	   Format: uuid
	*/
	TheaterID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the rooms show params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RoomsShowParams) WithDefaults() *RoomsShowParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the rooms show params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RoomsShowParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the rooms show params
func (o *RoomsShowParams) WithTimeout(timeout time.Duration) *RoomsShowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rooms show params
func (o *RoomsShowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rooms show params
func (o *RoomsShowParams) WithContext(ctx context.Context) *RoomsShowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rooms show params
func (o *RoomsShowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rooms show params
func (o *RoomsShowParams) WithHTTPClient(client *http.Client) *RoomsShowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rooms show params
func (o *RoomsShowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRoomID adds the roomID to the rooms show params
func (o *RoomsShowParams) WithRoomID(roomID strfmt.UUID) *RoomsShowParams {
	o.SetRoomID(roomID)
	return o
}

// SetRoomID adds the roomId to the rooms show params
func (o *RoomsShowParams) SetRoomID(roomID strfmt.UUID) {
	o.RoomID = roomID
}

// WithTheaterID adds the theaterID to the rooms show params
func (o *RoomsShowParams) WithTheaterID(theaterID strfmt.UUID) *RoomsShowParams {
	o.SetTheaterID(theaterID)
	return o
}

// SetTheaterID adds the theaterId to the rooms show params
func (o *RoomsShowParams) SetTheaterID(theaterID strfmt.UUID) {
	o.TheaterID = theaterID
}

// WriteToRequest writes these params to a swagger request
func (o *RoomsShowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param roomID
	if err := r.SetPathParam("roomID", o.RoomID.String()); err != nil {
		return err
	}

	// path param theaterID
	if err := r.SetPathParam("theaterID", o.TheaterID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
