// Code generated by go-swagger; DO NOT EDIT.

package rooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// RoomsUpdateReader is a Reader for the RoomsUpdate structure.
type RoomsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RoomsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewRoomsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRoomsUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRoomsUpdateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRoomsUpdateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /theaters/{theaterID}/rooms/{roomID}] RoomsUpdate", response, response.Code())
	}
}

// NewRoomsUpdateOK creates a RoomsUpdateOK with default headers values
func NewRoomsUpdateOK() *RoomsUpdateOK {
	return &RoomsUpdateOK{}
}

/*
RoomsUpdateOK describes a response with status code 200, with default header values.

OK
*/
type RoomsUpdateOK struct {
	Payload *models.APIRoomResponse
}

// IsSuccess returns true when this rooms update o k response has a 2xx status code
func (o *RoomsUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this rooms update o k response has a 3xx status code
func (o *RoomsUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms update o k response has a 4xx status code
func (o *RoomsUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this rooms update o k response has a 5xx status code
func (o *RoomsUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this rooms update o k response a status code equal to that given
func (o *RoomsUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the rooms update o k response
func (o *RoomsUpdateOK) Code() int {
	return 200
}

func (o *RoomsUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /theaters/{theaterID}/rooms/{roomID}][%d] roomsUpdateOK %s", 200, payload)
}

func (o *RoomsUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /theaters/{theaterID}/rooms/{roomID}][%d] roomsUpdateOK %s", 200, payload)
}

func (o *RoomsUpdateOK) GetPayload() *models.APIRoomResponse {
	return o.Payload
}

func (o *RoomsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIRoomResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRoomsUpdateBadRequest creates a RoomsUpdateBadRequest with default headers values
func NewRoomsUpdateBadRequest() *RoomsUpdateBadRequest {
	return &RoomsUpdateBadRequest{}
}

/*
RoomsUpdateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type RoomsUpdateBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this rooms update bad request response has a 2xx status code
func (o *RoomsUpdateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this rooms update bad request response has a 3xx status code
func (o *RoomsUpdateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms update bad request response has a 4xx status code
func (o *RoomsUpdateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this rooms update bad request response has a 5xx status code
func (o *RoomsUpdateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this rooms update bad request response a status code equal to that given
func (o *RoomsUpdateBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the rooms update bad request response
func (o *RoomsUpdateBadRequest) Code() int {
	return 400
}

func (o *RoomsUpdateBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /theaters/{theaterID}/rooms/{roomID}][%d] roomsUpdateBadRequest %s", 400, payload)
}

func (o *RoomsUpdateBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /theaters/{theaterID}/rooms/{roomID}][%d] roomsUpdateBadRequest %s", 400, payload)
}

func (o *RoomsUpdateBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RoomsUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRoomsUpdateNotFound creates a RoomsUpdateNotFound with default headers values
func NewRoomsUpdateNotFound() *RoomsUpdateNotFound {
	return &RoomsUpdateNotFound{}
}

/*
RoomsUpdateNotFound describes a response with status code 404, with default header values.

Not Found
*/
type RoomsUpdateNotFound struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this rooms update not found response has a 2xx status code
func (o *RoomsUpdateNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this rooms update not found response has a 3xx status code
func (o *RoomsUpdateNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms update not found response has a 4xx status code
func (o *RoomsUpdateNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this rooms update not found response has a 5xx status code
func (o *RoomsUpdateNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this rooms update not found response a status code equal to that given
func (o *RoomsUpdateNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the rooms update not found response
func (o *RoomsUpdateNotFound) Code() int {
	return 404
}

func (o *RoomsUpdateNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /theaters/{theaterID}/rooms/{roomID}][%d] roomsUpdateNotFound %s", 404, payload)
}

func (o *RoomsUpdateNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /theaters/{theaterID}/rooms/{roomID}][%d] roomsUpdateNotFound %s", 404, payload)
}

func (o *RoomsUpdateNotFound) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RoomsUpdateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRoomsUpdateInternalServerError creates a RoomsUpdateInternalServerError with default headers values
func NewRoomsUpdateInternalServerError() *RoomsUpdateInternalServerError {
	return &RoomsUpdateInternalServerError{}
}

/*
RoomsUpdateInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type RoomsUpdateInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this rooms update internal server error response has a 2xx status code
func (o *RoomsUpdateInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this rooms update internal server error response has a 3xx status code
func (o *RoomsUpdateInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms update internal server error response has a 4xx status code
func (o *RoomsUpdateInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this rooms update internal server error response has a 5xx status code
func (o *RoomsUpdateInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this rooms update internal server error response a status code equal to that given
func (o *RoomsUpdateInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the rooms update internal server error response
func (o *RoomsUpdateInternalServerError) Code() int {
	return 500
}

func (o *RoomsUpdateInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /theaters/{theaterID}/rooms/{roomID}][%d] roomsUpdateInternalServerError %s", 500, payload)
}

func (o *RoomsUpdateInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /theaters/{theaterID}/rooms/{roomID}][%d] roomsUpdateInternalServerError %s", 500, payload)
}

func (o *RoomsUpdateInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RoomsUpdateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
