// Code generated by go-swagger; DO NOT EDIT.

package rooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// NewRoomsCreateParams creates a new RoomsCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRoomsCreateParams() *RoomsCreateParams {
	return &RoomsCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRoomsCreateParamsWithTimeout creates a new RoomsCreateParams object
// with the ability to set a timeout on a request.
func NewRoomsCreateParamsWithTimeout(timeout time.Duration) *RoomsCreateParams {
	return &RoomsCreateParams{
		timeout: timeout,
	}
}

// NewRoomsCreateParamsWithContext creates a new RoomsCreateParams object
// with the ability to set a context for a request.
func NewRoomsCreateParamsWithContext(ctx context.Context) *RoomsCreateParams {
	return &RoomsCreateParams{
		Context: ctx,
	}
}

// NewRoomsCreateParamsWithHTTPClient creates a new RoomsCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewRoomsCreateParamsWithHTTPClient(client *http.Client) *RoomsCreateParams {
	return &RoomsCreateParams{
		HTTPClient: client,
	}
}

/*
RoomsCreateParams contains all the parameters to send to the API endpoint

	for the rooms create operation.

	Typically these are written to a http.Request.
*/
type RoomsCreateParams struct {

	/* Request.

	   request body
	*/
	Request *models.APIRoomRequest

	/* TheaterID.

	   Theater ID

	   Format: uuid
	*/
	TheaterID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the rooms create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RoomsCreateParams) WithDefaults() *RoomsCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the rooms create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RoomsCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the rooms create params
func (o *RoomsCreateParams) WithTimeout(timeout time.Duration) *RoomsCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rooms create params
func (o *RoomsCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rooms create params
func (o *RoomsCreateParams) WithContext(ctx context.Context) *RoomsCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rooms create params
func (o *RoomsCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rooms create params
func (o *RoomsCreateParams) WithHTTPClient(client *http.Client) *RoomsCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rooms create params
func (o *RoomsCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the rooms create params
func (o *RoomsCreateParams) WithRequest(request *models.APIRoomRequest) *RoomsCreateParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the rooms create params
func (o *RoomsCreateParams) SetRequest(request *models.APIRoomRequest) {
	o.Request = request
}

// WithTheaterID adds the theaterID to the rooms create params
func (o *RoomsCreateParams) WithTheaterID(theaterID strfmt.UUID) *RoomsCreateParams {
	o.SetTheaterID(theaterID)
	return o
}

// SetTheaterID adds the theaterId to the rooms create params
func (o *RoomsCreateParams) SetTheaterID(theaterID strfmt.UUID) {
	o.TheaterID = theaterID
}

// WriteToRequest writes these params to a swagger request
func (o *RoomsCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// path param theaterID
	if err := r.SetPathParam("theaterID", o.TheaterID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
