// Code generated by go-swagger; DO NOT EDIT.

package rooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new rooms API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new rooms API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new rooms API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for rooms API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	RoomsCreate(params *RoomsCreateParams, opts ...ClientOption) (*RoomsCreateOK, error)

	RoomsDelete(params *RoomsDeleteParams, opts ...ClientOption) (*RoomsDeleteNoContent, error)

	RoomsList(params *RoomsListParams, opts ...ClientOption) (*RoomsListOK, error)

	RoomsShow(params *RoomsShowParams, opts ...ClientOption) (*RoomsShowOK, error)

	RoomsUpdate(params *RoomsUpdateParams, opts ...ClientOption) (*RoomsUpdateOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
RoomsCreate creates room

Create room
*/
func (a *Client) RoomsCreate(params *RoomsCreateParams, opts ...ClientOption) (*RoomsCreateOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewRoomsCreateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "RoomsCreate",
		Method:             "POST",
		PathPattern:        "/theaters/{theaterID}/rooms",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &RoomsCreateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*RoomsCreateOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for RoomsCreate: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
RoomsDelete deletes room

Delete room
*/
func (a *Client) RoomsDelete(params *RoomsDeleteParams, opts ...ClientOption) (*RoomsDeleteNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewRoomsDeleteParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "RoomsDelete",
		Method:             "DELETE",
		PathPattern:        "/theaters/{theaterID}/rooms/{roomID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &RoomsDeleteReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*RoomsDeleteNoContent)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for RoomsDelete: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
RoomsList lists rooms

List rooms
*/
func (a *Client) RoomsList(params *RoomsListParams, opts ...ClientOption) (*RoomsListOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewRoomsListParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "RoomsList",
		Method:             "GET",
		PathPattern:        "/theaters/{theaterID}/rooms",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &RoomsListReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*RoomsListOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for RoomsList: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
RoomsShow shows room

Show room
*/
func (a *Client) RoomsShow(params *RoomsShowParams, opts ...ClientOption) (*RoomsShowOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewRoomsShowParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "RoomsShow",
		Method:             "GET",
		PathPattern:        "/theaters/{theaterID}/rooms/{roomID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &RoomsShowReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*RoomsShowOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for RoomsShow: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
RoomsUpdate updates room

Update room
*/
func (a *Client) RoomsUpdate(params *RoomsUpdateParams, opts ...ClientOption) (*RoomsUpdateOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewRoomsUpdateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "RoomsUpdate",
		Method:             "PUT",
		PathPattern:        "/theaters/{theaterID}/rooms/{roomID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &RoomsUpdateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*RoomsUpdateOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for RoomsUpdate: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
