// Code generated by go-swagger; DO NOT EDIT.

package rooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// RoomsDeleteReader is a Reader for the RoomsDelete structure.
type RoomsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RoomsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewRoomsDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRoomsDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRoomsDeleteNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRoomsDeleteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /theaters/{theaterID}/rooms/{roomID}] RoomsDelete", response, response.Code())
	}
}

// NewRoomsDeleteNoContent creates a RoomsDeleteNoContent with default headers values
func NewRoomsDeleteNoContent() *RoomsDeleteNoContent {
	return &RoomsDeleteNoContent{}
}

/*
RoomsDeleteNoContent describes a response with status code 204, with default header values.

No Content
*/
type RoomsDeleteNoContent struct {
}

// IsSuccess returns true when this rooms delete no content response has a 2xx status code
func (o *RoomsDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this rooms delete no content response has a 3xx status code
func (o *RoomsDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms delete no content response has a 4xx status code
func (o *RoomsDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this rooms delete no content response has a 5xx status code
func (o *RoomsDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this rooms delete no content response a status code equal to that given
func (o *RoomsDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the rooms delete no content response
func (o *RoomsDeleteNoContent) Code() int {
	return 204
}

func (o *RoomsDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /theaters/{theaterID}/rooms/{roomID}][%d] roomsDeleteNoContent", 204)
}

func (o *RoomsDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /theaters/{theaterID}/rooms/{roomID}][%d] roomsDeleteNoContent", 204)
}

func (o *RoomsDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRoomsDeleteBadRequest creates a RoomsDeleteBadRequest with default headers values
func NewRoomsDeleteBadRequest() *RoomsDeleteBadRequest {
	return &RoomsDeleteBadRequest{}
}

/*
RoomsDeleteBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type RoomsDeleteBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this rooms delete bad request response has a 2xx status code
func (o *RoomsDeleteBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this rooms delete bad request response has a 3xx status code
func (o *RoomsDeleteBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms delete bad request response has a 4xx status code
func (o *RoomsDeleteBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this rooms delete bad request response has a 5xx status code
func (o *RoomsDeleteBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this rooms delete bad request response a status code equal to that given
func (o *RoomsDeleteBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the rooms delete bad request response
func (o *RoomsDeleteBadRequest) Code() int {
	return 400
}

func (o *RoomsDeleteBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /theaters/{theaterID}/rooms/{roomID}][%d] roomsDeleteBadRequest %s", 400, payload)
}

func (o *RoomsDeleteBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /theaters/{theaterID}/rooms/{roomID}][%d] roomsDeleteBadRequest %s", 400, payload)
}

func (o *RoomsDeleteBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RoomsDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRoomsDeleteNotFound creates a RoomsDeleteNotFound with default headers values
func NewRoomsDeleteNotFound() *RoomsDeleteNotFound {
	return &RoomsDeleteNotFound{}
}

/*
RoomsDeleteNotFound describes a response with status code 404, with default header values.

Not Found
*/
type RoomsDeleteNotFound struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this rooms delete not found response has a 2xx status code
func (o *RoomsDeleteNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this rooms delete not found response has a 3xx status code
func (o *RoomsDeleteNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms delete not found response has a 4xx status code
func (o *RoomsDeleteNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this rooms delete not found response has a 5xx status code
func (o *RoomsDeleteNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this rooms delete not found response a status code equal to that given
func (o *RoomsDeleteNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the rooms delete not found response
func (o *RoomsDeleteNotFound) Code() int {
	return 404
}

func (o *RoomsDeleteNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /theaters/{theaterID}/rooms/{roomID}][%d] roomsDeleteNotFound %s", 404, payload)
}

func (o *RoomsDeleteNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /theaters/{theaterID}/rooms/{roomID}][%d] roomsDeleteNotFound %s", 404, payload)
}

func (o *RoomsDeleteNotFound) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RoomsDeleteNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRoomsDeleteInternalServerError creates a RoomsDeleteInternalServerError with default headers values
func NewRoomsDeleteInternalServerError() *RoomsDeleteInternalServerError {
	return &RoomsDeleteInternalServerError{}
}

/*
RoomsDeleteInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type RoomsDeleteInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this rooms delete internal server error response has a 2xx status code
func (o *RoomsDeleteInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this rooms delete internal server error response has a 3xx status code
func (o *RoomsDeleteInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms delete internal server error response has a 4xx status code
func (o *RoomsDeleteInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this rooms delete internal server error response has a 5xx status code
func (o *RoomsDeleteInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this rooms delete internal server error response a status code equal to that given
func (o *RoomsDeleteInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the rooms delete internal server error response
func (o *RoomsDeleteInternalServerError) Code() int {
	return 500
}

func (o *RoomsDeleteInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /theaters/{theaterID}/rooms/{roomID}][%d] roomsDeleteInternalServerError %s", 500, payload)
}

func (o *RoomsDeleteInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /theaters/{theaterID}/rooms/{roomID}][%d] roomsDeleteInternalServerError %s", 500, payload)
}

func (o *RoomsDeleteInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RoomsDeleteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
