// Code generated by go-swagger; DO NOT EDIT.

package rooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// RoomsCreateReader is a Reader for the RoomsCreate structure.
type RoomsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RoomsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewRoomsCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRoomsCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRoomsCreateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRoomsCreateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /theaters/{theaterID}/rooms] RoomsCreate", response, response.Code())
	}
}

// NewRoomsCreateOK creates a RoomsCreateOK with default headers values
func NewRoomsCreateOK() *RoomsCreateOK {
	return &RoomsCreateOK{}
}

/*
RoomsCreateOK describes a response with status code 200, with default header values.

OK
*/
type RoomsCreateOK struct {
	Payload *models.APIRoomResponse
}

// IsSuccess returns true when this rooms create o k response has a 2xx status code
func (o *RoomsCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this rooms create o k response has a 3xx status code
func (o *RoomsCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms create o k response has a 4xx status code
func (o *RoomsCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this rooms create o k response has a 5xx status code
func (o *RoomsCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this rooms create o k response a status code equal to that given
func (o *RoomsCreateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the rooms create o k response
func (o *RoomsCreateOK) Code() int {
	return 200
}

func (o *RoomsCreateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /theaters/{theaterID}/rooms][%d] roomsCreateOK %s", 200, payload)
}

func (o *RoomsCreateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /theaters/{theaterID}/rooms][%d] roomsCreateOK %s", 200, payload)
}

func (o *RoomsCreateOK) GetPayload() *models.APIRoomResponse {
	return o.Payload
}

func (o *RoomsCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIRoomResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRoomsCreateBadRequest creates a RoomsCreateBadRequest with default headers values
func NewRoomsCreateBadRequest() *RoomsCreateBadRequest {
	return &RoomsCreateBadRequest{}
}

/*
RoomsCreateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type RoomsCreateBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this rooms create bad request response has a 2xx status code
func (o *RoomsCreateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this rooms create bad request response has a 3xx status code
func (o *RoomsCreateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms create bad request response has a 4xx status code
func (o *RoomsCreateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this rooms create bad request response has a 5xx status code
func (o *RoomsCreateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this rooms create bad request response a status code equal to that given
func (o *RoomsCreateBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the rooms create bad request response
func (o *RoomsCreateBadRequest) Code() int {
	return 400
}

func (o *RoomsCreateBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /theaters/{theaterID}/rooms][%d] roomsCreateBadRequest %s", 400, payload)
}

func (o *RoomsCreateBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /theaters/{theaterID}/rooms][%d] roomsCreateBadRequest %s", 400, payload)
}

func (o *RoomsCreateBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RoomsCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRoomsCreateNotFound creates a RoomsCreateNotFound with default headers values
func NewRoomsCreateNotFound() *RoomsCreateNotFound {
	return &RoomsCreateNotFound{}
}

/*
RoomsCreateNotFound describes a response with status code 404, with default header values.

Not Found
*/
type RoomsCreateNotFound struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this rooms create not found response has a 2xx status code
func (o *RoomsCreateNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this rooms create not found response has a 3xx status code
func (o *RoomsCreateNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms create not found response has a 4xx status code
func (o *RoomsCreateNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this rooms create not found response has a 5xx status code
func (o *RoomsCreateNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this rooms create not found response a status code equal to that given
func (o *RoomsCreateNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the rooms create not found response
func (o *RoomsCreateNotFound) Code() int {
	return 404
}

func (o *RoomsCreateNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /theaters/{theaterID}/rooms][%d] roomsCreateNotFound %s", 404, payload)
}

func (o *RoomsCreateNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /theaters/{theaterID}/rooms][%d] roomsCreateNotFound %s", 404, payload)
}

func (o *RoomsCreateNotFound) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RoomsCreateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRoomsCreateInternalServerError creates a RoomsCreateInternalServerError with default headers values
func NewRoomsCreateInternalServerError() *RoomsCreateInternalServerError {
	return &RoomsCreateInternalServerError{}
}

/*
RoomsCreateInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type RoomsCreateInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this rooms create internal server error response has a 2xx status code
func (o *RoomsCreateInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this rooms create internal server error response has a 3xx status code
func (o *RoomsCreateInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms create internal server error response has a 4xx status code
func (o *RoomsCreateInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this rooms create internal server error response has a 5xx status code
func (o *RoomsCreateInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this rooms create internal server error response a status code equal to that given
func (o *RoomsCreateInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the rooms create internal server error response
func (o *RoomsCreateInternalServerError) Code() int {
	return 500
}

func (o *RoomsCreateInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /theaters/{theaterID}/rooms][%d] roomsCreateInternalServerError %s", 500, payload)
}

func (o *RoomsCreateInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /theaters/{theaterID}/rooms][%d] roomsCreateInternalServerError %s", 500, payload)
}

func (o *RoomsCreateInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RoomsCreateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
