// Code generated by go-swagger; DO NOT EDIT.

package rooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// RoomsShowReader is a Reader for the RoomsShow structure.
type RoomsShowReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RoomsShowReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewRoomsShowOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRoomsShowBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRoomsShowNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRoomsShowInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /theaters/{theaterID}/rooms/{roomID}] RoomsShow", response, response.Code())
	}
}

// NewRoomsShowOK creates a RoomsShowOK with default headers values
func NewRoomsShowOK() *RoomsShowOK {
	return &RoomsShowOK{}
}

/*
RoomsShowOK describes a response with status code 200, with default header values.

OK
*/
type RoomsShowOK struct {
	Payload *models.APIRoomResponse
}

// IsSuccess returns true when this rooms show o k response has a 2xx status code
func (o *RoomsShowOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this rooms show o k response has a 3xx status code
func (o *RoomsShowOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms show o k response has a 4xx status code
func (o *RoomsShowOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this rooms show o k response has a 5xx status code
func (o *RoomsShowOK) IsServerError() bool {
	return false
}

// IsCode returns true when this rooms show o k response a status code equal to that given
func (o *RoomsShowOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the rooms show o k response
func (o *RoomsShowOK) Code() int {
	return 200
}

func (o *RoomsShowOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}][%d] roomsShowOK %s", 200, payload)
}

func (o *RoomsShowOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}][%d] roomsShowOK %s", 200, payload)
}

func (o *RoomsShowOK) GetPayload() *models.APIRoomResponse {
	return o.Payload
}

func (o *RoomsShowOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIRoomResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRoomsShowBadRequest creates a RoomsShowBadRequest with default headers values
func NewRoomsShowBadRequest() *RoomsShowBadRequest {
	return &RoomsShowBadRequest{}
}

/*
RoomsShowBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type RoomsShowBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this rooms show bad request response has a 2xx status code
func (o *RoomsShowBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this rooms show bad request response has a 3xx status code
func (o *RoomsShowBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms show bad request response has a 4xx status code
func (o *RoomsShowBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this rooms show bad request response has a 5xx status code
func (o *RoomsShowBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this rooms show bad request response a status code equal to that given
func (o *RoomsShowBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the rooms show bad request response
func (o *RoomsShowBadRequest) Code() int {
	return 400
}

func (o *RoomsShowBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}][%d] roomsShowBadRequest %s", 400, payload)
}

func (o *RoomsShowBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}][%d] roomsShowBadRequest %s", 400, payload)
}

func (o *RoomsShowBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RoomsShowBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRoomsShowNotFound creates a RoomsShowNotFound with default headers values
func NewRoomsShowNotFound() *RoomsShowNotFound {
	return &RoomsShowNotFound{}
}

/*
RoomsShowNotFound describes a response with status code 404, with default header values.

Not Found
*/
type RoomsShowNotFound struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this rooms show not found response has a 2xx status code
func (o *RoomsShowNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this rooms show not found response has a 3xx status code
func (o *RoomsShowNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms show not found response has a 4xx status code
func (o *RoomsShowNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this rooms show not found response has a 5xx status code
func (o *RoomsShowNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this rooms show not found response a status code equal to that given
func (o *RoomsShowNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the rooms show not found response
func (o *RoomsShowNotFound) Code() int {
	return 404
}

func (o *RoomsShowNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}][%d] roomsShowNotFound %s", 404, payload)
}

func (o *RoomsShowNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}][%d] roomsShowNotFound %s", 404, payload)
}

func (o *RoomsShowNotFound) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RoomsShowNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRoomsShowInternalServerError creates a RoomsShowInternalServerError with default headers values
func NewRoomsShowInternalServerError() *RoomsShowInternalServerError {
	return &RoomsShowInternalServerError{}
}

/*
RoomsShowInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type RoomsShowInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this rooms show internal server error response has a 2xx status code
func (o *RoomsShowInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this rooms show internal server error response has a 3xx status code
func (o *RoomsShowInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rooms show internal server error response has a 4xx status code
func (o *RoomsShowInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this rooms show internal server error response has a 5xx status code
func (o *RoomsShowInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this rooms show internal server error response a status code equal to that given
func (o *RoomsShowInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the rooms show internal server error response
func (o *RoomsShowInternalServerError) Code() int {
	return 500
}

func (o *RoomsShowInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}][%d] roomsShowInternalServerError %s", 500, payload)
}

func (o *RoomsShowInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}/rooms/{roomID}][%d] roomsShowInternalServerError %s", 500, payload)
}

func (o *RoomsShowInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RoomsShowInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
