// Code generated by go-swagger; DO NOT EDIT.

package theaters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// TheatersUpdateReader is a Reader for the TheatersUpdate structure.
type TheatersUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TheatersUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewTheatersUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewTheatersUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewTheatersUpdateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewTheatersUpdateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /theaters/{theaterID}] TheatersUpdate", response, response.Code())
	}
}

// NewTheatersUpdateOK creates a TheatersUpdateOK with default headers values
func NewTheatersUpdateOK() *TheatersUpdateOK {
	return &TheatersUpdateOK{}
}

/*
TheatersUpdateOK describes a response with status code 200, with default header values.

OK
*/
type TheatersUpdateOK struct {
	Payload *models.APITheaterResponse
}

// IsSuccess returns true when this theaters update o k response has a 2xx status code
func (o *TheatersUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this theaters update o k response has a 3xx status code
func (o *TheatersUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this theaters update o k response has a 4xx status code
func (o *TheatersUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this theaters update o k response has a 5xx status code
func (o *TheatersUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this theaters update o k response a status code equal to that given
func (o *TheatersUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the theaters update o k response
func (o *TheatersUpdateOK) Code() int {
	return 200
}

func (o *TheatersUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /theaters/{theaterID}][%d] theatersUpdateOK %s", 200, payload)
}

func (o *TheatersUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /theaters/{theaterID}][%d] theatersUpdateOK %s", 200, payload)
}

func (o *TheatersUpdateOK) GetPayload() *models.APITheaterResponse {
	return o.Payload
}

func (o *TheatersUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APITheaterResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTheatersUpdateBadRequest creates a TheatersUpdateBadRequest with default headers values
func NewTheatersUpdateBadRequest() *TheatersUpdateBadRequest {
	return &TheatersUpdateBadRequest{}
}

/*
TheatersUpdateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type TheatersUpdateBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this theaters update bad request response has a 2xx status code
func (o *TheatersUpdateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this theaters update bad request response has a 3xx status code
func (o *TheatersUpdateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this theaters update bad request response has a 4xx status code
func (o *TheatersUpdateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this theaters update bad request response has a 5xx status code
func (o *TheatersUpdateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this theaters update bad request response a status code equal to that given
func (o *TheatersUpdateBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the theaters update bad request response
func (o *TheatersUpdateBadRequest) Code() int {
	return 400
}

func (o *TheatersUpdateBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /theaters/{theaterID}][%d] theatersUpdateBadRequest %s", 400, payload)
}

func (o *TheatersUpdateBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /theaters/{theaterID}][%d] theatersUpdateBadRequest %s", 400, payload)
}

func (o *TheatersUpdateBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TheatersUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTheatersUpdateNotFound creates a TheatersUpdateNotFound with default headers values
func NewTheatersUpdateNotFound() *TheatersUpdateNotFound {
	return &TheatersUpdateNotFound{}
}

/*
TheatersUpdateNotFound describes a response with status code 404, with default header values.

Not Found
*/
type TheatersUpdateNotFound struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this theaters update not found response has a 2xx status code
func (o *TheatersUpdateNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this theaters update not found response has a 3xx status code
func (o *TheatersUpdateNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this theaters update not found response has a 4xx status code
func (o *TheatersUpdateNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this theaters update not found response has a 5xx status code
func (o *TheatersUpdateNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this theaters update not found response a status code equal to that given
func (o *TheatersUpdateNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the theaters update not found response
func (o *TheatersUpdateNotFound) Code() int {
	return 404
}

func (o *TheatersUpdateNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /theaters/{theaterID}][%d] theatersUpdateNotFound %s", 404, payload)
}

func (o *TheatersUpdateNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /theaters/{theaterID}][%d] theatersUpdateNotFound %s", 404, payload)
}

func (o *TheatersUpdateNotFound) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TheatersUpdateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTheatersUpdateInternalServerError creates a TheatersUpdateInternalServerError with default headers values
func NewTheatersUpdateInternalServerError() *TheatersUpdateInternalServerError {
	return &TheatersUpdateInternalServerError{}
}

/*
TheatersUpdateInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type TheatersUpdateInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this theaters update internal server error response has a 2xx status code
func (o *TheatersUpdateInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this theaters update internal server error response has a 3xx status code
func (o *TheatersUpdateInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this theaters update internal server error response has a 4xx status code
func (o *TheatersUpdateInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this theaters update internal server error response has a 5xx status code
func (o *TheatersUpdateInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this theaters update internal server error response a status code equal to that given
func (o *TheatersUpdateInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the theaters update internal server error response
func (o *TheatersUpdateInternalServerError) Code() int {
	return 500
}

func (o *TheatersUpdateInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /theaters/{theaterID}][%d] theatersUpdateInternalServerError %s", 500, payload)
}

func (o *TheatersUpdateInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /theaters/{theaterID}][%d] theatersUpdateInternalServerError %s", 500, payload)
}

func (o *TheatersUpdateInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TheatersUpdateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
