// Code generated by go-swagger; DO NOT EDIT.

package theaters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewTheatersShowParams creates a new TheatersShowParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTheatersShowParams() *TheatersShowParams {
	return &TheatersShowParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTheatersShowParamsWithTimeout creates a new TheatersShowParams object
// with the ability to set a timeout on a request.
func NewTheatersShowParamsWithTimeout(timeout time.Duration) *TheatersShowParams {
	return &TheatersShowParams{
		timeout: timeout,
	}
}

// NewTheatersShowParamsWithContext creates a new TheatersShowParams object
// with the ability to set a context for a request.
func NewTheatersShowParamsWithContext(ctx context.Context) *TheatersShowParams {
	return &TheatersShowParams{
		Context: ctx,
	}
}

// NewTheatersShowParamsWithHTTPClient creates a new TheatersShowParams object
// with the ability to set a custom HTTPClient for a request.
func NewTheatersShowParamsWithHTTPClient(client *http.Client) *TheatersShowParams {
	return &TheatersShowParams{
		HTTPClient: client,
	}
}

/*
TheatersShowParams contains all the parameters to send to the API endpoint

	for the theaters show operation.

	Typically these are written to a http.Request.
*/
type TheatersShowParams struct {

	/* TheaterID.

	   Theater ID

	   Format: uuid
	*/
	TheaterID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the theaters show params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TheatersShowParams) WithDefaults() *TheatersShowParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the theaters show params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TheatersShowParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the theaters show params
func (o *TheatersShowParams) WithTimeout(timeout time.Duration) *TheatersShowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the theaters show params
func (o *TheatersShowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the theaters show params
func (o *TheatersShowParams) WithContext(ctx context.Context) *TheatersShowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the theaters show params
func (o *TheatersShowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the theaters show params
func (o *TheatersShowParams) WithHTTPClient(client *http.Client) *TheatersShowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the theaters show params
func (o *TheatersShowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTheaterID adds the theaterID to the theaters show params
func (o *TheatersShowParams) WithTheaterID(theaterID strfmt.UUID) *TheatersShowParams {
	o.SetTheaterID(theaterID)
	return o
}

// SetTheaterID adds the theaterId to the theaters show params
func (o *TheatersShowParams) SetTheaterID(theaterID strfmt.UUID) {
	o.TheaterID = theaterID
}

// WriteToRequest writes these params to a swagger request
func (o *TheatersShowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param theaterID
	if err := r.SetPathParam("theaterID", o.TheaterID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
