// Code generated by go-swagger; DO NOT EDIT.

package theaters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// NewTheatersCreateParams creates a new TheatersCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTheatersCreateParams() *TheatersCreateParams {
	return &TheatersCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTheatersCreateParamsWithTimeout creates a new TheatersCreateParams object
// with the ability to set a timeout on a request.
func NewTheatersCreateParamsWithTimeout(timeout time.Duration) *TheatersCreateParams {
	return &TheatersCreateParams{
		timeout: timeout,
	}
}

// NewTheatersCreateParamsWithContext creates a new TheatersCreateParams object
// with the ability to set a context for a request.
func NewTheatersCreateParamsWithContext(ctx context.Context) *TheatersCreateParams {
	return &TheatersCreateParams{
		Context: ctx,
	}
}

// NewTheatersCreateParamsWithHTTPClient creates a new TheatersCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewTheatersCreateParamsWithHTTPClient(client *http.Client) *TheatersCreateParams {
	return &TheatersCreateParams{
		HTTPClient: client,
	}
}

/*
TheatersCreateParams contains all the parameters to send to the API endpoint

	for the theaters create operation.

	Typically these are written to a http.Request.
*/
type TheatersCreateParams struct {

	/* Request.

	   request body
	*/
	Request *models.APITheaterRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the theaters create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TheatersCreateParams) WithDefaults() *TheatersCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the theaters create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TheatersCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the theaters create params
func (o *TheatersCreateParams) WithTimeout(timeout time.Duration) *TheatersCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the theaters create params
func (o *TheatersCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the theaters create params
func (o *TheatersCreateParams) WithContext(ctx context.Context) *TheatersCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the theaters create params
func (o *TheatersCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the theaters create params
func (o *TheatersCreateParams) WithHTTPClient(client *http.Client) *TheatersCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the theaters create params
func (o *TheatersCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the theaters create params
func (o *TheatersCreateParams) WithRequest(request *models.APITheaterRequest) *TheatersCreateParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the theaters create params
func (o *TheatersCreateParams) SetRequest(request *models.APITheaterRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *TheatersCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
