// Code generated by go-swagger; DO NOT EDIT.

package theaters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// TheatersCreateReader is a Reader for the TheatersCreate structure.
type TheatersCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TheatersCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewTheatersCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewTheatersCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewTheatersCreateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewTheatersCreateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /theaters] TheatersCreate", response, response.Code())
	}
}

// NewTheatersCreateOK creates a TheatersCreateOK with default headers values
func NewTheatersCreateOK() *TheatersCreateOK {
	return &TheatersCreateOK{}
}

/*
TheatersCreateOK describes a response with status code 200, with default header values.

OK
*/
type TheatersCreateOK struct {
	Payload *models.APITheaterResponse
}

// IsSuccess returns true when this theaters create o k response has a 2xx status code
func (o *TheatersCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this theaters create o k response has a 3xx status code
func (o *TheatersCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this theaters create o k response has a 4xx status code
func (o *TheatersCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this theaters create o k response has a 5xx status code
func (o *TheatersCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this theaters create o k response a status code equal to that given
func (o *TheatersCreateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the theaters create o k response
func (o *TheatersCreateOK) Code() int {
	return 200
}

func (o *TheatersCreateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /theaters][%d] theatersCreateOK %s", 200, payload)
}

func (o *TheatersCreateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /theaters][%d] theatersCreateOK %s", 200, payload)
}

func (o *TheatersCreateOK) GetPayload() *models.APITheaterResponse {
	return o.Payload
}

func (o *TheatersCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APITheaterResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTheatersCreateBadRequest creates a TheatersCreateBadRequest with default headers values
func NewTheatersCreateBadRequest() *TheatersCreateBadRequest {
	return &TheatersCreateBadRequest{}
}

/*
TheatersCreateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type TheatersCreateBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this theaters create bad request response has a 2xx status code
func (o *TheatersCreateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this theaters create bad request response has a 3xx status code
func (o *TheatersCreateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this theaters create bad request response has a 4xx status code
func (o *TheatersCreateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this theaters create bad request response has a 5xx status code
func (o *TheatersCreateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this theaters create bad request response a status code equal to that given
func (o *TheatersCreateBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the theaters create bad request response
func (o *TheatersCreateBadRequest) Code() int {
	return 400
}

func (o *TheatersCreateBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /theaters][%d] theatersCreateBadRequest %s", 400, payload)
}

func (o *TheatersCreateBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /theaters][%d] theatersCreateBadRequest %s", 400, payload)
}

func (o *TheatersCreateBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TheatersCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTheatersCreateNotFound creates a TheatersCreateNotFound with default headers values
func NewTheatersCreateNotFound() *TheatersCreateNotFound {
	return &TheatersCreateNotFound{}
}

/*
TheatersCreateNotFound describes a response with status code 404, with default header values.

Not Found
*/
type TheatersCreateNotFound struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this theaters create not found response has a 2xx status code
func (o *TheatersCreateNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this theaters create not found response has a 3xx status code
func (o *TheatersCreateNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this theaters create not found response has a 4xx status code
func (o *TheatersCreateNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this theaters create not found response has a 5xx status code
func (o *TheatersCreateNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this theaters create not found response a status code equal to that given
func (o *TheatersCreateNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the theaters create not found response
func (o *TheatersCreateNotFound) Code() int {
	return 404
}

func (o *TheatersCreateNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /theaters][%d] theatersCreateNotFound %s", 404, payload)
}

func (o *TheatersCreateNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /theaters][%d] theatersCreateNotFound %s", 404, payload)
}

func (o *TheatersCreateNotFound) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TheatersCreateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTheatersCreateInternalServerError creates a TheatersCreateInternalServerError with default headers values
func NewTheatersCreateInternalServerError() *TheatersCreateInternalServerError {
	return &TheatersCreateInternalServerError{}
}

/*
TheatersCreateInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type TheatersCreateInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this theaters create internal server error response has a 2xx status code
func (o *TheatersCreateInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this theaters create internal server error response has a 3xx status code
func (o *TheatersCreateInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this theaters create internal server error response has a 4xx status code
func (o *TheatersCreateInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this theaters create internal server error response has a 5xx status code
func (o *TheatersCreateInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this theaters create internal server error response a status code equal to that given
func (o *TheatersCreateInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the theaters create internal server error response
func (o *TheatersCreateInternalServerError) Code() int {
	return 500
}

func (o *TheatersCreateInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /theaters][%d] theatersCreateInternalServerError %s", 500, payload)
}

func (o *TheatersCreateInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /theaters][%d] theatersCreateInternalServerError %s", 500, payload)
}

func (o *TheatersCreateInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TheatersCreateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
