// Code generated by go-swagger; DO NOT EDIT.

package theaters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// TheatersShowReader is a Reader for the TheatersShow structure.
type TheatersShowReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TheatersShowReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewTheatersShowOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewTheatersShowBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewTheatersShowNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewTheatersShowInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /theaters/{theaterID}] TheatersShow", response, response.Code())
	}
}

// NewTheatersShowOK creates a TheatersShowOK with default headers values
func NewTheatersShowOK() *TheatersShowOK {
	return &TheatersShowOK{}
}

/*
TheatersShowOK describes a response with status code 200, with default header values.

OK
*/
type TheatersShowOK struct {
	Payload *models.APITheaterResponse
}

// IsSuccess returns true when this theaters show o k response has a 2xx status code
func (o *TheatersShowOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this theaters show o k response has a 3xx status code
func (o *TheatersShowOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this theaters show o k response has a 4xx status code
func (o *TheatersShowOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this theaters show o k response has a 5xx status code
func (o *TheatersShowOK) IsServerError() bool {
	return false
}

// IsCode returns true when this theaters show o k response a status code equal to that given
func (o *TheatersShowOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the theaters show o k response
func (o *TheatersShowOK) Code() int {
	return 200
}

func (o *TheatersShowOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}][%d] theatersShowOK %s", 200, payload)
}

func (o *TheatersShowOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}][%d] theatersShowOK %s", 200, payload)
}

func (o *TheatersShowOK) GetPayload() *models.APITheaterResponse {
	return o.Payload
}

func (o *TheatersShowOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APITheaterResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTheatersShowBadRequest creates a TheatersShowBadRequest with default headers values
func NewTheatersShowBadRequest() *TheatersShowBadRequest {
	return &TheatersShowBadRequest{}
}

/*
TheatersShowBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type TheatersShowBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this theaters show bad request response has a 2xx status code
func (o *TheatersShowBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this theaters show bad request response has a 3xx status code
func (o *TheatersShowBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this theaters show bad request response has a 4xx status code
func (o *TheatersShowBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this theaters show bad request response has a 5xx status code
func (o *TheatersShowBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this theaters show bad request response a status code equal to that given
func (o *TheatersShowBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the theaters show bad request response
func (o *TheatersShowBadRequest) Code() int {
	return 400
}

func (o *TheatersShowBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}][%d] theatersShowBadRequest %s", 400, payload)
}

func (o *TheatersShowBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}][%d] theatersShowBadRequest %s", 400, payload)
}

func (o *TheatersShowBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TheatersShowBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTheatersShowNotFound creates a TheatersShowNotFound with default headers values
func NewTheatersShowNotFound() *TheatersShowNotFound {
	return &TheatersShowNotFound{}
}

/*
TheatersShowNotFound describes a response with status code 404, with default header values.

Not Found
*/
type TheatersShowNotFound struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this theaters show not found response has a 2xx status code
func (o *TheatersShowNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this theaters show not found response has a 3xx status code
func (o *TheatersShowNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this theaters show not found response has a 4xx status code
func (o *TheatersShowNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this theaters show not found response has a 5xx status code
func (o *TheatersShowNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this theaters show not found response a status code equal to that given
func (o *TheatersShowNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the theaters show not found response
func (o *TheatersShowNotFound) Code() int {
	return 404
}

func (o *TheatersShowNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}][%d] theatersShowNotFound %s", 404, payload)
}

func (o *TheatersShowNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}][%d] theatersShowNotFound %s", 404, payload)
}

func (o *TheatersShowNotFound) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TheatersShowNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTheatersShowInternalServerError creates a TheatersShowInternalServerError with default headers values
func NewTheatersShowInternalServerError() *TheatersShowInternalServerError {
	return &TheatersShowInternalServerError{}
}

/*
TheatersShowInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type TheatersShowInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this theaters show internal server error response has a 2xx status code
func (o *TheatersShowInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this theaters show internal server error response has a 3xx status code
func (o *TheatersShowInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this theaters show internal server error response has a 4xx status code
func (o *TheatersShowInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this theaters show internal server error response has a 5xx status code
func (o *TheatersShowInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this theaters show internal server error response a status code equal to that given
func (o *TheatersShowInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the theaters show internal server error response
func (o *TheatersShowInternalServerError) Code() int {
	return 500
}

func (o *TheatersShowInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}][%d] theatersShowInternalServerError %s", 500, payload)
}

func (o *TheatersShowInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters/{theaterID}][%d] theatersShowInternalServerError %s", 500, payload)
}

func (o *TheatersShowInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TheatersShowInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
