// Code generated by go-swagger; DO NOT EDIT.

package theaters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// NewTheatersUpdateParams creates a new TheatersUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTheatersUpdateParams() *TheatersUpdateParams {
	return &TheatersUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTheatersUpdateParamsWithTimeout creates a new TheatersUpdateParams object
// with the ability to set a timeout on a request.
func NewTheatersUpdateParamsWithTimeout(timeout time.Duration) *TheatersUpdateParams {
	return &TheatersUpdateParams{
		timeout: timeout,
	}
}

// NewTheatersUpdateParamsWithContext creates a new TheatersUpdateParams object
// with the ability to set a context for a request.
func NewTheatersUpdateParamsWithContext(ctx context.Context) *TheatersUpdateParams {
	return &TheatersUpdateParams{
		Context: ctx,
	}
}

// NewTheatersUpdateParamsWithHTTPClient creates a new TheatersUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewTheatersUpdateParamsWithHTTPClient(client *http.Client) *TheatersUpdateParams {
	return &TheatersUpdateParams{
		HTTPClient: client,
	}
}

/*
TheatersUpdateParams contains all the parameters to send to the API endpoint

	for the theaters update operation.

	Typically these are written to a http.Request.
*/
type TheatersUpdateParams struct {

	/* Request.

	   request body
	*/
	Request *models.APITheaterRequest

	/* TheaterID.

	   Theater ID

	   Format: uuid
	*/
	TheaterID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the theaters update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TheatersUpdateParams) WithDefaults() *TheatersUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the theaters update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TheatersUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the theaters update params
func (o *TheatersUpdateParams) WithTimeout(timeout time.Duration) *TheatersUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the theaters update params
func (o *TheatersUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the theaters update params
func (o *TheatersUpdateParams) WithContext(ctx context.Context) *TheatersUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the theaters update params
func (o *TheatersUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the theaters update params
func (o *TheatersUpdateParams) WithHTTPClient(client *http.Client) *TheatersUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the theaters update params
func (o *TheatersUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the theaters update params
func (o *TheatersUpdateParams) WithRequest(request *models.APITheaterRequest) *TheatersUpdateParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the theaters update params
func (o *TheatersUpdateParams) SetRequest(request *models.APITheaterRequest) {
	o.Request = request
}

// WithTheaterID adds the theaterID to the theaters update params
func (o *TheatersUpdateParams) WithTheaterID(theaterID strfmt.UUID) *TheatersUpdateParams {
	o.SetTheaterID(theaterID)
	return o
}

// SetTheaterID adds the theaterId to the theaters update params
func (o *TheatersUpdateParams) SetTheaterID(theaterID strfmt.UUID) {
	o.TheaterID = theaterID
}

// WriteToRequest writes these params to a swagger request
func (o *TheatersUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// path param theaterID
	if err := r.SetPathParam("theaterID", o.TheaterID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
