// Code generated by go-swagger; DO NOT EDIT.

package theaters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// TheatersListReader is a Reader for the TheatersList structure.
type TheatersListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TheatersListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewTheatersListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewTheatersListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewTheatersListNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewTheatersListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /theaters] TheatersList", response, response.Code())
	}
}

// NewTheatersListOK creates a TheatersListOK with default headers values
func NewTheatersListOK() *TheatersListOK {
	return &TheatersListOK{}
}

/*
TheatersListOK describes a response with status code 200, with default header values.

OK
*/
type TheatersListOK struct {
	Payload []*models.APITheaterResponse
}

// IsSuccess returns true when this theaters list o k response has a 2xx status code
func (o *TheatersListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this theaters list o k response has a 3xx status code
func (o *TheatersListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this theaters list o k response has a 4xx status code
func (o *TheatersListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this theaters list o k response has a 5xx status code
func (o *TheatersListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this theaters list o k response a status code equal to that given
func (o *TheatersListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the theaters list o k response
func (o *TheatersListOK) Code() int {
	return 200
}

func (o *TheatersListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters][%d] theatersListOK %s", 200, payload)
}

func (o *TheatersListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters][%d] theatersListOK %s", 200, payload)
}

func (o *TheatersListOK) GetPayload() []*models.APITheaterResponse {
	return o.Payload
}

func (o *TheatersListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTheatersListBadRequest creates a TheatersListBadRequest with default headers values
func NewTheatersListBadRequest() *TheatersListBadRequest {
	return &TheatersListBadRequest{}
}

/*
TheatersListBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type TheatersListBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this theaters list bad request response has a 2xx status code
func (o *TheatersListBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this theaters list bad request response has a 3xx status code
func (o *TheatersListBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this theaters list bad request response has a 4xx status code
func (o *TheatersListBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this theaters list bad request response has a 5xx status code
func (o *TheatersListBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this theaters list bad request response a status code equal to that given
func (o *TheatersListBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the theaters list bad request response
func (o *TheatersListBadRequest) Code() int {
	return 400
}

func (o *TheatersListBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters][%d] theatersListBadRequest %s", 400, payload)
}

func (o *TheatersListBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters][%d] theatersListBadRequest %s", 400, payload)
}

func (o *TheatersListBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TheatersListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTheatersListNotFound creates a TheatersListNotFound with default headers values
func NewTheatersListNotFound() *TheatersListNotFound {
	return &TheatersListNotFound{}
}

/*
TheatersListNotFound describes a response with status code 404, with default header values.

Not Found
*/
type TheatersListNotFound struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this theaters list not found response has a 2xx status code
func (o *TheatersListNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this theaters list not found response has a 3xx status code
func (o *TheatersListNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this theaters list not found response has a 4xx status code
func (o *TheatersListNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this theaters list not found response has a 5xx status code
func (o *TheatersListNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this theaters list not found response a status code equal to that given
func (o *TheatersListNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the theaters list not found response
func (o *TheatersListNotFound) Code() int {
	return 404
}

func (o *TheatersListNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters][%d] theatersListNotFound %s", 404, payload)
}

func (o *TheatersListNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters][%d] theatersListNotFound %s", 404, payload)
}

func (o *TheatersListNotFound) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TheatersListNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTheatersListInternalServerError creates a TheatersListInternalServerError with default headers values
func NewTheatersListInternalServerError() *TheatersListInternalServerError {
	return &TheatersListInternalServerError{}
}

/*
TheatersListInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type TheatersListInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this theaters list internal server error response has a 2xx status code
func (o *TheatersListInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this theaters list internal server error response has a 3xx status code
func (o *TheatersListInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this theaters list internal server error response has a 4xx status code
func (o *TheatersListInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this theaters list internal server error response has a 5xx status code
func (o *TheatersListInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this theaters list internal server error response a status code equal to that given
func (o *TheatersListInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the theaters list internal server error response
func (o *TheatersListInternalServerError) Code() int {
	return 500
}

func (o *TheatersListInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters][%d] theatersListInternalServerError %s", 500, payload)
}

func (o *TheatersListInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /theaters][%d] theatersListInternalServerError %s", 500, payload)
}

func (o *TheatersListInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TheatersListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
