// Code generated by go-swagger; DO NOT EDIT.

package theaters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/reklame/clients/spored/models"
)

// TheatersDeleteReader is a Reader for the TheatersDelete structure.
type TheatersDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TheatersDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewTheatersDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewTheatersDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewTheatersDeleteNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewTheatersDeleteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /theaters/{theaterID}] TheatersDelete", response, response.Code())
	}
}

// NewTheatersDeleteNoContent creates a TheatersDeleteNoContent with default headers values
func NewTheatersDeleteNoContent() *TheatersDeleteNoContent {
	return &TheatersDeleteNoContent{}
}

/*
TheatersDeleteNoContent describes a response with status code 204, with default header values.

No Content
*/
type TheatersDeleteNoContent struct {
}

// IsSuccess returns true when this theaters delete no content response has a 2xx status code
func (o *TheatersDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this theaters delete no content response has a 3xx status code
func (o *TheatersDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this theaters delete no content response has a 4xx status code
func (o *TheatersDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this theaters delete no content response has a 5xx status code
func (o *TheatersDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this theaters delete no content response a status code equal to that given
func (o *TheatersDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the theaters delete no content response
func (o *TheatersDeleteNoContent) Code() int {
	return 204
}

func (o *TheatersDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /theaters/{theaterID}][%d] theatersDeleteNoContent", 204)
}

func (o *TheatersDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /theaters/{theaterID}][%d] theatersDeleteNoContent", 204)
}

func (o *TheatersDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewTheatersDeleteBadRequest creates a TheatersDeleteBadRequest with default headers values
func NewTheatersDeleteBadRequest() *TheatersDeleteBadRequest {
	return &TheatersDeleteBadRequest{}
}

/*
TheatersDeleteBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type TheatersDeleteBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this theaters delete bad request response has a 2xx status code
func (o *TheatersDeleteBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this theaters delete bad request response has a 3xx status code
func (o *TheatersDeleteBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this theaters delete bad request response has a 4xx status code
func (o *TheatersDeleteBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this theaters delete bad request response has a 5xx status code
func (o *TheatersDeleteBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this theaters delete bad request response a status code equal to that given
func (o *TheatersDeleteBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the theaters delete bad request response
func (o *TheatersDeleteBadRequest) Code() int {
	return 400
}

func (o *TheatersDeleteBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /theaters/{theaterID}][%d] theatersDeleteBadRequest %s", 400, payload)
}

func (o *TheatersDeleteBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /theaters/{theaterID}][%d] theatersDeleteBadRequest %s", 400, payload)
}

func (o *TheatersDeleteBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TheatersDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTheatersDeleteNotFound creates a TheatersDeleteNotFound with default headers values
func NewTheatersDeleteNotFound() *TheatersDeleteNotFound {
	return &TheatersDeleteNotFound{}
}

/*
TheatersDeleteNotFound describes a response with status code 404, with default header values.

Not Found
*/
type TheatersDeleteNotFound struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this theaters delete not found response has a 2xx status code
func (o *TheatersDeleteNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this theaters delete not found response has a 3xx status code
func (o *TheatersDeleteNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this theaters delete not found response has a 4xx status code
func (o *TheatersDeleteNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this theaters delete not found response has a 5xx status code
func (o *TheatersDeleteNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this theaters delete not found response a status code equal to that given
func (o *TheatersDeleteNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the theaters delete not found response
func (o *TheatersDeleteNotFound) Code() int {
	return 404
}

func (o *TheatersDeleteNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /theaters/{theaterID}][%d] theatersDeleteNotFound %s", 404, payload)
}

func (o *TheatersDeleteNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /theaters/{theaterID}][%d] theatersDeleteNotFound %s", 404, payload)
}

func (o *TheatersDeleteNotFound) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TheatersDeleteNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTheatersDeleteInternalServerError creates a TheatersDeleteInternalServerError with default headers values
func NewTheatersDeleteInternalServerError() *TheatersDeleteInternalServerError {
	return &TheatersDeleteInternalServerError{}
}

/*
TheatersDeleteInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type TheatersDeleteInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this theaters delete internal server error response has a 2xx status code
func (o *TheatersDeleteInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this theaters delete internal server error response has a 3xx status code
func (o *TheatersDeleteInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this theaters delete internal server error response has a 4xx status code
func (o *TheatersDeleteInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this theaters delete internal server error response has a 5xx status code
func (o *TheatersDeleteInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this theaters delete internal server error response a status code equal to that given
func (o *TheatersDeleteInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the theaters delete internal server error response
func (o *TheatersDeleteInternalServerError) Code() int {
	return 500
}

func (o *TheatersDeleteInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /theaters/{theaterID}][%d] theatersDeleteInternalServerError %s", 500, payload)
}

func (o *TheatersDeleteInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /theaters/{theaterID}][%d] theatersDeleteInternalServerError %s", 500, payload)
}

func (o *TheatersDeleteInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *TheatersDeleteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
