// Code generated by go-swagger; DO NOT EDIT.

package theaters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new theaters API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new theaters API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new theaters API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for theaters API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	TheatersCreate(params *TheatersCreateParams, opts ...ClientOption) (*TheatersCreateOK, error)

	TheatersDelete(params *TheatersDeleteParams, opts ...ClientOption) (*TheatersDeleteNoContent, error)

	TheatersList(params *TheatersListParams, opts ...ClientOption) (*TheatersListOK, error)

	TheatersShow(params *TheatersShowParams, opts ...ClientOption) (*TheatersShowOK, error)

	TheatersUpdate(params *TheatersUpdateParams, opts ...ClientOption) (*TheatersUpdateOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
TheatersCreate creates theater

Create theater
*/
func (a *Client) TheatersCreate(params *TheatersCreateParams, opts ...ClientOption) (*TheatersCreateOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewTheatersCreateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "TheatersCreate",
		Method:             "POST",
		PathPattern:        "/theaters",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &TheatersCreateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*TheatersCreateOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for TheatersCreate: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
TheatersDelete deletes theater

Delete theater
*/
func (a *Client) TheatersDelete(params *TheatersDeleteParams, opts ...ClientOption) (*TheatersDeleteNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewTheatersDeleteParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "TheatersDelete",
		Method:             "DELETE",
		PathPattern:        "/theaters/{theaterID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &TheatersDeleteReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*TheatersDeleteNoContent)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for TheatersDelete: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
TheatersList lists theaters

List theaters
*/
func (a *Client) TheatersList(params *TheatersListParams, opts ...ClientOption) (*TheatersListOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewTheatersListParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "TheatersList",
		Method:             "GET",
		PathPattern:        "/theaters",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &TheatersListReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*TheatersListOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for TheatersList: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
TheatersShow shows theater

Show theater
*/
func (a *Client) TheatersShow(params *TheatersShowParams, opts ...ClientOption) (*TheatersShowOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewTheatersShowParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "TheatersShow",
		Method:             "GET",
		PathPattern:        "/theaters/{theaterID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &TheatersShowReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*TheatersShowOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for TheatersShow: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
TheatersUpdate updates theater

Update theater
*/
func (a *Client) TheatersUpdate(params *TheatersUpdateParams, opts ...ClientOption) (*TheatersUpdateOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewTheatersUpdateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "TheatersUpdate",
		Method:             "PUT",
		PathPattern:        "/theaters/{theaterID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &TheatersUpdateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*TheatersUpdateOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for TheatersUpdate: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
